// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module enhanced_correlator_sin_or_cos_float_s (
        ap_clk,
        ap_rst,
        t_in,
        do_cos,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] t_in;
input  [0:0] do_cos;
output  [31:0] ap_return;

wire   [3:0] ref_4oPi_table_100_address0;
wire   [99:0] ref_4oPi_table_100_q0;
wire   [7:0] second_order_float_sin_cos_K0_address0;
wire   [29:0] second_order_float_sin_cos_K0_q0;
wire   [7:0] second_order_float_sin_cos_K1_address0;
wire   [22:0] second_order_float_sin_cos_K1_q0;
wire   [7:0] second_order_float_sin_cos_K2_address0;
wire   [14:0] second_order_float_sin_cos_K2_q0;
reg   [0:0] do_cos_read_reg_1205;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] do_cos_read_reg_1205_pp0_iter1_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter2_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter3_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter4_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter5_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter6_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter7_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter8_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter9_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter10_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter11_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter12_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter13_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter14_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter15_reg;
reg   [0:0] do_cos_read_reg_1205_pp0_iter16_reg;
reg   [0:0] din_sign_reg_1213;
reg   [0:0] din_sign_reg_1213_pp0_iter1_reg;
reg   [0:0] din_sign_reg_1213_pp0_iter2_reg;
reg   [0:0] din_sign_reg_1213_pp0_iter3_reg;
reg   [0:0] din_sign_reg_1213_pp0_iter4_reg;
reg   [0:0] din_sign_reg_1213_pp0_iter5_reg;
reg   [0:0] din_sign_reg_1213_pp0_iter6_reg;
reg   [0:0] din_sign_reg_1213_pp0_iter7_reg;
wire   [7:0] din_exp_fu_312_p3;
reg   [7:0] din_exp_reg_1219;
reg   [7:0] din_exp_reg_1219_pp0_iter1_reg;
reg   [7:0] din_exp_reg_1219_pp0_iter2_reg;
reg   [7:0] din_exp_reg_1219_pp0_iter3_reg;
reg   [7:0] din_exp_reg_1219_pp0_iter4_reg;
reg   [7:0] din_exp_reg_1219_pp0_iter5_reg;
reg   [7:0] din_exp_reg_1219_pp0_iter6_reg;
reg   [7:0] din_exp_reg_1219_pp0_iter7_reg;
wire   [22:0] din_sig_fu_320_p1;
reg   [22:0] din_sig_reg_1226;
reg   [22:0] din_sig_reg_1226_pp0_iter1_reg;
wire   [0:0] closepath_fu_324_p2;
reg   [0:0] closepath_reg_1232;
reg   [0:0] closepath_reg_1232_pp0_iter1_reg;
reg   [0:0] closepath_reg_1232_pp0_iter2_reg;
reg   [0:0] closepath_reg_1232_pp0_iter3_reg;
reg   [0:0] closepath_reg_1232_pp0_iter4_reg;
reg   [0:0] closepath_reg_1232_pp0_iter5_reg;
reg   [0:0] closepath_reg_1232_pp0_iter6_reg;
reg   [0:0] closepath_reg_1232_pp0_iter7_reg;
wire   [3:0] trunc_ln379_fu_359_p1;
reg   [3:0] trunc_ln379_reg_1243;
reg  signed [79:0] Med_reg_1248;
wire   [0:0] icmp_ln271_1_fu_392_p2;
reg   [0:0] icmp_ln271_1_reg_1258;
reg   [0:0] icmp_ln271_1_reg_1258_pp0_iter3_reg;
reg   [0:0] icmp_ln271_1_reg_1258_pp0_iter4_reg;
reg   [0:0] icmp_ln271_1_reg_1258_pp0_iter5_reg;
reg   [0:0] icmp_ln271_1_reg_1258_pp0_iter6_reg;
reg   [0:0] icmp_ln271_1_reg_1258_pp0_iter7_reg;
reg   [57:0] Mx_bits_reg_1263;
reg   [2:0] trunc_ln_reg_1269;
wire   [2:0] k_fu_417_p3;
reg   [2:0] k_reg_1274;
wire   [57:0] Mx_bits_3_fu_432_p3;
reg   [57:0] Mx_bits_3_reg_1279;
reg   [28:0] tmp_7_reg_1284;
wire   [0:0] tmp_s_fu_447_p19;
reg   [0:0] tmp_s_reg_1289;
reg   [28:0] Mx_reg_1296;
wire   [7:0] Ex_1_fu_537_p2;
reg   [7:0] Ex_1_reg_1302;
reg   [0:0] tmp_reg_1308;
wire   [7:0] sub_ln506_fu_551_p2;
reg   [7:0] sub_ln506_reg_1314;
wire   [0:0] cos_basis_fu_562_p3;
reg   [0:0] cos_basis_reg_1319;
wire   [0:0] sin_basis_fu_568_p3;
reg   [0:0] sin_basis_reg_1325;
reg   [0:0] sin_basis_reg_1325_pp0_iter9_reg;
wire   [0:0] and_ln271_fu_737_p2;
reg   [0:0] and_ln271_reg_1330;
reg   [0:0] and_ln271_reg_1330_pp0_iter9_reg;
reg   [0:0] and_ln271_reg_1330_pp0_iter10_reg;
reg   [0:0] and_ln271_reg_1330_pp0_iter11_reg;
reg   [0:0] and_ln271_reg_1330_pp0_iter12_reg;
reg   [0:0] and_ln271_reg_1330_pp0_iter13_reg;
reg   [0:0] and_ln271_reg_1330_pp0_iter14_reg;
reg   [0:0] and_ln271_reg_1330_pp0_iter15_reg;
reg   [0:0] and_ln271_reg_1330_pp0_iter16_reg;
wire   [0:0] icmp_ln282_fu_752_p2;
reg   [0:0] icmp_ln282_reg_1336;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter9_reg;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter10_reg;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter11_reg;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter12_reg;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter13_reg;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter14_reg;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter15_reg;
reg   [0:0] icmp_ln282_reg_1336_pp0_iter16_reg;
wire   [0:0] results_sign_3_fu_769_p3;
reg   [0:0] results_sign_3_reg_1343;
reg   [0:0] results_sign_3_reg_1343_pp0_iter9_reg;
reg   [0:0] results_sign_3_reg_1343_pp0_iter10_reg;
reg   [0:0] results_sign_3_reg_1343_pp0_iter11_reg;
reg   [0:0] results_sign_3_reg_1343_pp0_iter12_reg;
reg   [0:0] results_sign_3_reg_1343_pp0_iter13_reg;
reg   [0:0] results_sign_3_reg_1343_pp0_iter14_reg;
reg   [0:0] results_sign_3_reg_1343_pp0_iter15_reg;
reg   [0:0] results_sign_3_reg_1343_pp0_iter16_reg;
wire   [21:0] B_fu_808_p1;
reg   [21:0] B_reg_1348;
reg   [21:0] B_reg_1348_pp0_iter10_reg;
reg   [21:0] B_reg_1348_pp0_iter11_reg;
wire   [28:0] Mx_1_fu_812_p3;
reg   [28:0] Mx_1_reg_1353;
reg   [28:0] Mx_1_reg_1353_pp0_iter10_reg;
reg   [28:0] Mx_1_reg_1353_pp0_iter11_reg;
reg   [28:0] Mx_1_reg_1353_pp0_iter12_reg;
reg   [28:0] Mx_1_reg_1353_pp0_iter13_reg;
wire   [7:0] Ex_2_fu_818_p3;
reg   [7:0] Ex_2_reg_1358;
reg   [7:0] Ex_2_reg_1358_pp0_iter10_reg;
reg   [7:0] Ex_2_reg_1358_pp0_iter11_reg;
reg   [7:0] Ex_2_reg_1358_pp0_iter12_reg;
reg   [7:0] Ex_2_reg_1358_pp0_iter13_reg;
reg   [7:0] Ex_2_reg_1358_pp0_iter14_reg;
reg   [7:0] Ex_2_reg_1358_pp0_iter15_reg;
reg   [7:0] Ex_2_reg_1358_pp0_iter16_reg;
reg   [6:0] tmp_1_reg_1363;
reg   [14:0] B_trunc_reg_1368;
reg   [14:0] B_trunc_reg_1368_pp0_iter10_reg;
reg   [14:0] B_squared_reg_1388;
reg   [28:0] t1_reg_1393;
reg   [28:0] t1_reg_1393_pp0_iter12_reg;
reg  signed [22:0] second_order_float_sin_cos_K1_load_reg_1398;
reg  signed [14:0] second_order_float_sin_cos_K2_load_reg_1403;
reg   [21:0] trunc_ln2_reg_1408;
reg   [13:0] trunc_ln3_reg_1413;
wire   [29:0] add_ln32_1_fu_941_p2;
reg  signed [29:0] add_ln32_1_reg_1418;
reg   [28:0] result_reg_1433;
reg   [15:0] tmp_3_reg_1438;
reg   [12:0] tmp_4_reg_1443;
reg   [27:0] trunc_ln5_reg_1448;
wire   [4:0] trunc_ln281_fu_1017_p1;
reg   [4:0] trunc_ln281_reg_1453;
wire   [3:0] trunc_ln281_1_fu_1033_p1;
reg   [3:0] trunc_ln281_1_reg_1458;
wire   [27:0] in_shift_1_fu_1037_p2;
reg   [27:0] in_shift_1_reg_1464;
wire   [0:0] icmp_ln292_fu_1042_p2;
reg   [0:0] icmp_ln292_reg_1470;
wire   [0:0] icmp_ln306_fu_1048_p2;
reg   [0:0] icmp_ln306_reg_1476;
wire   [63:0] zext_ln378_fu_354_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln28_fu_850_p1;
reg    ref_4oPi_table_100_ce0_local;
reg    second_order_float_sin_cos_K0_ce0_local;
reg    second_order_float_sin_cos_K1_ce0_local;
reg    second_order_float_sin_cos_K2_ce0_local;
wire   [21:0] mul_ln29_fu_288_p1;
wire   [28:0] grp_fu_292_p1;
wire   [23:0] grp_fu_296_p1;
wire   [31:0] data_fu_300_p1;
wire   [7:0] add_ln376_fu_330_p2;
wire   [7:0] addr_fu_336_p3;
wire   [3:0] lshr_ln_fu_344_p4;
wire   [99:0] zext_ln379_fu_363_p1;
wire   [99:0] shl_ln379_fu_366_p2;
wire   [23:0] X_fu_380_p3;
wire   [79:0] grp_fu_296_p2;
wire   [0:0] trunc_ln491_fu_423_p1;
wire   [57:0] Mx_bits_1_fu_427_p2;
wire   [0:0] tmp_s_fu_447_p17;
wire   [7:0] Ex_fu_487_p2;
wire   [29:0] Mx_zeros_fu_506_p1;
wire   [29:0] Mx_zeros_fu_506_p3;
wire   [57:0] zext_ln504_fu_514_p1;
wire   [57:0] shl_ln504_fu_518_p2;
wire   [7:0] select_ln453_fu_492_p3;
wire   [7:0] trunc_ln505_fu_533_p1;
wire   [0:0] xor_ln242_fu_557_p2;
wire   [0:0] tmp_8_fu_580_p33;
wire   [3:0] index_fu_574_p3;
wire   [0:0] tmp_5_fu_652_p33;
wire   [0:0] tmp_8_fu_580_p35;
wire   [0:0] tmp_5_fu_652_p35;
wire   [0:0] icmp_ln271_fu_732_p2;
wire   [0:0] xor_ln278_fu_742_p2;
wire   [0:0] results_sign_fu_724_p3;
wire   [0:0] xor_ln282_fu_757_p2;
wire   [0:0] results_sign_2_fu_747_p2;
wire   [0:0] results_sign_4_fu_763_p2;
wire   [7:0] select_ln506_fu_777_p3;
wire   [31:0] zext_ln506_fu_786_p1;
wire   [31:0] zext_ln506_1_fu_782_p1;
wire   [31:0] lshr_ln506_fu_789_p2;
wire   [31:0] shl_ln506_fu_795_p2;
wire   [31:0] select_ln506_1_fu_801_p3;
wire   [7:0] A_fu_844_p3;
wire   [14:0] mul_ln23_fu_860_p0;
wire   [29:0] zext_ln23_fu_857_p1;
wire   [14:0] mul_ln23_fu_860_p1;
wire   [29:0] mul_ln23_fu_860_p2;
wire   [44:0] mul_ln29_fu_288_p2;
wire   [14:0] mul_ln30_fu_910_p0;
wire   [29:0] mul_ln30_fu_910_p2;
wire  signed [29:0] sext_ln32_fu_926_p1;
wire  signed [29:0] sext_ln32_1_fu_929_p1;
wire   [29:0] add_ln32_fu_932_p2;
wire  signed [29:0] sext_ln32_2_fu_938_p1;
wire   [57:0] grp_fu_292_p2;
wire   [31:0] c_fu_1009_p1;
wire   [31:0] c_fu_1009_p3;
wire   [31:0] c_1_fu_1025_p1;
wire   [31:0] c_1_fu_1025_p3;
wire   [27:0] zext_ln281_fu_1021_p1;
wire   [27:0] zext_ln281_1_fu_1056_p1;
wire   [4:0] shift_1_fu_1059_p3;
wire   [4:0] shift_2_fu_1071_p3;
wire  signed [8:0] sext_ln252_fu_1053_p1;
wire   [8:0] add_ln300_fu_1081_p2;
wire   [8:0] zext_ln286_fu_1077_p1;
wire   [8:0] newexp_fu_1087_p2;
wire   [0:0] tmp_2_fu_1093_p3;
wire   [27:0] in_shift_2_fu_1066_p2;
wire   [22:0] tmp_6_fu_1110_p4;
wire   [22:0] tmp_9_fu_1120_p4;
wire   [0:0] or_ln306_fu_1101_p2;
wire   [0:0] or_ln282_fu_1150_p2;
wire   [7:0] select_ln282_fu_1143_p3;
wire   [7:0] empty_fu_1106_p1;
wire   [22:0] select_ln282_2_fu_1163_p3;
wire   [22:0] empty_59_fu_1129_p3;
wire   [7:0] select_ln259_fu_1136_p3;
wire   [7:0] results_exp_fu_1155_p3;
wire   [22:0] results_sig_fu_1170_p3;
wire   [7:0] results_exp_1_fu_1178_p3;
wire   [22:0] results_sig_1_fu_1185_p3;
wire   [31:0] t_2_fu_1192_p4;
reg   [31:0] t_in_int_reg;
reg   [0:0] do_cos_int_reg;
wire   [57:0] grp_fu_292_p10;
wire   [79:0] grp_fu_296_p10;
wire   [44:0] mul_ln29_fu_288_p10;
wire   [29:0] mul_ln30_fu_910_p00;
wire   [2:0] tmp_s_fu_447_p1;
wire   [2:0] tmp_s_fu_447_p3;
wire   [2:0] tmp_s_fu_447_p5;
wire   [2:0] tmp_s_fu_447_p7;
wire  signed [2:0] tmp_s_fu_447_p9;
wire  signed [2:0] tmp_s_fu_447_p11;
wire  signed [2:0] tmp_s_fu_447_p13;
wire  signed [2:0] tmp_s_fu_447_p15;
wire   [29:0] Mx_zeros_fu_506_p0;
wire   [0:0] Mx_zeros_fu_506_p2;
wire   [3:0] tmp_8_fu_580_p1;
wire   [3:0] tmp_8_fu_580_p3;
wire   [3:0] tmp_8_fu_580_p5;
wire   [3:0] tmp_8_fu_580_p7;
wire   [3:0] tmp_8_fu_580_p9;
wire   [3:0] tmp_8_fu_580_p11;
wire   [3:0] tmp_8_fu_580_p13;
wire   [3:0] tmp_8_fu_580_p15;
wire  signed [3:0] tmp_8_fu_580_p17;
wire  signed [3:0] tmp_8_fu_580_p19;
wire  signed [3:0] tmp_8_fu_580_p21;
wire  signed [3:0] tmp_8_fu_580_p23;
wire  signed [3:0] tmp_8_fu_580_p25;
wire  signed [3:0] tmp_8_fu_580_p27;
wire  signed [3:0] tmp_8_fu_580_p29;
wire  signed [3:0] tmp_8_fu_580_p31;
wire   [3:0] tmp_5_fu_652_p1;
wire   [3:0] tmp_5_fu_652_p3;
wire   [3:0] tmp_5_fu_652_p5;
wire   [3:0] tmp_5_fu_652_p7;
wire   [3:0] tmp_5_fu_652_p9;
wire   [3:0] tmp_5_fu_652_p11;
wire   [3:0] tmp_5_fu_652_p13;
wire   [3:0] tmp_5_fu_652_p15;
wire  signed [3:0] tmp_5_fu_652_p17;
wire  signed [3:0] tmp_5_fu_652_p19;
wire  signed [3:0] tmp_5_fu_652_p21;
wire  signed [3:0] tmp_5_fu_652_p23;
wire  signed [3:0] tmp_5_fu_652_p25;
wire  signed [3:0] tmp_5_fu_652_p27;
wire  signed [3:0] tmp_5_fu_652_p29;
wire  signed [3:0] tmp_5_fu_652_p31;
wire   [31:0] c_fu_1009_p0;
wire   [0:0] c_fu_1009_p2;
wire   [31:0] c_1_fu_1025_p0;
wire   [0:0] c_1_fu_1025_p2;
wire    ap_ce_reg;

enhanced_correlator_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_address0),
    .ce0(ref_4oPi_table_100_ce0_local),
    .q0(ref_4oPi_table_100_q0)
);

enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K0_address0),
    .ce0(second_order_float_sin_cos_K0_ce0_local),
    .q0(second_order_float_sin_cos_K0_q0)
);

enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K1_address0),
    .ce0(second_order_float_sin_cos_K1_ce0_local),
    .q0(second_order_float_sin_cos_K1_q0)
);

enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K2_address0),
    .ce0(second_order_float_sin_cos_K2_ce0_local),
    .q0(second_order_float_sin_cos_K2_q0)
);

enhanced_correlator_mul_23s_22ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 45 ))
mul_23s_22ns_45_1_1_U1(
    .din0(second_order_float_sin_cos_K1_load_reg_1398),
    .din1(mul_ln29_fu_288_p1),
    .dout(mul_ln29_fu_288_p2)
);

enhanced_correlator_mul_30s_29ns_58_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_30s_29ns_58_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln32_1_reg_1418),
    .din1(grp_fu_292_p1),
    .ce(1'b1),
    .dout(grp_fu_292_p2)
);

enhanced_correlator_mul_80s_24ns_80_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 80 ))
mul_80s_24ns_80_5_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Med_reg_1248),
    .din1(grp_fu_296_p1),
    .ce(1'b1),
    .dout(grp_fu_296_p2)
);

(* dissolve_hierarchy = "yes" *) enhanced_correlator_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U4(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .def(tmp_s_fu_447_p17),
    .sel(k_fu_417_p3),
    .dout(tmp_s_fu_447_p19)
);

enhanced_correlator_ctlz_30_30_1_1 #(
    .din_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
ctlz_30_30_1_1_U5(
    .din(Mx_zeros_fu_506_p1),
    .dout(Mx_zeros_fu_506_p3)
);

(* dissolve_hierarchy = "yes" *) enhanced_correlator_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U6(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_8_fu_580_p33),
    .sel(index_fu_574_p3),
    .dout(tmp_8_fu_580_p35)
);

(* dissolve_hierarchy = "yes" *) enhanced_correlator_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U7(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_5_fu_652_p33),
    .sel(index_fu_574_p3),
    .dout(tmp_5_fu_652_p35)
);

enhanced_correlator_mul_15ns_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15ns_30_1_1_U8(
    .din0(mul_ln23_fu_860_p0),
    .din1(mul_ln23_fu_860_p1),
    .dout(mul_ln23_fu_860_p2)
);

enhanced_correlator_mul_15ns_15s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15s_30_1_1_U9(
    .din0(mul_ln30_fu_910_p0),
    .din1(second_order_float_sin_cos_K2_load_reg_1403),
    .dout(mul_ln30_fu_910_p2)
);

enhanced_correlator_ctlz_32_32_1_1 #(
    .din_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ctlz_32_32_1_1_U10(
    .din(c_fu_1009_p1),
    .dout(c_fu_1009_p3)
);

enhanced_correlator_ctlz_32_32_1_1 #(
    .din_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ctlz_32_32_1_1_U11(
    .din(c_1_fu_1025_p1),
    .dout(c_1_fu_1025_p3)
);

always @ (posedge ap_clk) begin
    do_cos_int_reg <= do_cos;
end

always @ (posedge ap_clk) begin
    t_in_int_reg <= t_in;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        B_reg_1348 <= B_fu_808_p1;
        B_reg_1348_pp0_iter10_reg <= B_reg_1348;
        B_reg_1348_pp0_iter11_reg <= B_reg_1348_pp0_iter10_reg;
        B_squared_reg_1388 <= {{mul_ln23_fu_860_p2[29:15]}};
        B_trunc_reg_1368 <= {{select_ln506_1_fu_801_p3[21:7]}};
        B_trunc_reg_1368_pp0_iter10_reg <= B_trunc_reg_1368;
        Ex_1_reg_1302 <= Ex_1_fu_537_p2;
        Ex_2_reg_1358 <= Ex_2_fu_818_p3;
        Ex_2_reg_1358_pp0_iter10_reg <= Ex_2_reg_1358;
        Ex_2_reg_1358_pp0_iter11_reg <= Ex_2_reg_1358_pp0_iter10_reg;
        Ex_2_reg_1358_pp0_iter12_reg <= Ex_2_reg_1358_pp0_iter11_reg;
        Ex_2_reg_1358_pp0_iter13_reg <= Ex_2_reg_1358_pp0_iter12_reg;
        Ex_2_reg_1358_pp0_iter14_reg <= Ex_2_reg_1358_pp0_iter13_reg;
        Ex_2_reg_1358_pp0_iter15_reg <= Ex_2_reg_1358_pp0_iter14_reg;
        Ex_2_reg_1358_pp0_iter16_reg <= Ex_2_reg_1358_pp0_iter15_reg;
        Med_reg_1248 <= {{shl_ln379_fu_366_p2[99:20]}};
        Mx_1_reg_1353 <= Mx_1_fu_812_p3;
        Mx_1_reg_1353_pp0_iter10_reg <= Mx_1_reg_1353;
        Mx_1_reg_1353_pp0_iter11_reg <= Mx_1_reg_1353_pp0_iter10_reg;
        Mx_1_reg_1353_pp0_iter12_reg <= Mx_1_reg_1353_pp0_iter11_reg;
        Mx_1_reg_1353_pp0_iter13_reg <= Mx_1_reg_1353_pp0_iter12_reg;
        Mx_bits_3_reg_1279 <= Mx_bits_3_fu_432_p3;
        Mx_bits_reg_1263 <= {{grp_fu_296_p2[76:19]}};
        Mx_reg_1296 <= {{shl_ln504_fu_518_p2[57:29]}};
        add_ln32_1_reg_1418 <= add_ln32_1_fu_941_p2;
        and_ln271_reg_1330 <= and_ln271_fu_737_p2;
        and_ln271_reg_1330_pp0_iter10_reg <= and_ln271_reg_1330_pp0_iter9_reg;
        and_ln271_reg_1330_pp0_iter11_reg <= and_ln271_reg_1330_pp0_iter10_reg;
        and_ln271_reg_1330_pp0_iter12_reg <= and_ln271_reg_1330_pp0_iter11_reg;
        and_ln271_reg_1330_pp0_iter13_reg <= and_ln271_reg_1330_pp0_iter12_reg;
        and_ln271_reg_1330_pp0_iter14_reg <= and_ln271_reg_1330_pp0_iter13_reg;
        and_ln271_reg_1330_pp0_iter15_reg <= and_ln271_reg_1330_pp0_iter14_reg;
        and_ln271_reg_1330_pp0_iter16_reg <= and_ln271_reg_1330_pp0_iter15_reg;
        and_ln271_reg_1330_pp0_iter9_reg <= and_ln271_reg_1330;
        closepath_reg_1232 <= closepath_fu_324_p2;
        closepath_reg_1232_pp0_iter1_reg <= closepath_reg_1232;
        closepath_reg_1232_pp0_iter2_reg <= closepath_reg_1232_pp0_iter1_reg;
        closepath_reg_1232_pp0_iter3_reg <= closepath_reg_1232_pp0_iter2_reg;
        closepath_reg_1232_pp0_iter4_reg <= closepath_reg_1232_pp0_iter3_reg;
        closepath_reg_1232_pp0_iter5_reg <= closepath_reg_1232_pp0_iter4_reg;
        closepath_reg_1232_pp0_iter6_reg <= closepath_reg_1232_pp0_iter5_reg;
        closepath_reg_1232_pp0_iter7_reg <= closepath_reg_1232_pp0_iter6_reg;
        cos_basis_reg_1319 <= cos_basis_fu_562_p3;
        din_exp_reg_1219 <= {{data_fu_300_p1[30:23]}};
        din_exp_reg_1219_pp0_iter1_reg <= din_exp_reg_1219;
        din_exp_reg_1219_pp0_iter2_reg <= din_exp_reg_1219_pp0_iter1_reg;
        din_exp_reg_1219_pp0_iter3_reg <= din_exp_reg_1219_pp0_iter2_reg;
        din_exp_reg_1219_pp0_iter4_reg <= din_exp_reg_1219_pp0_iter3_reg;
        din_exp_reg_1219_pp0_iter5_reg <= din_exp_reg_1219_pp0_iter4_reg;
        din_exp_reg_1219_pp0_iter6_reg <= din_exp_reg_1219_pp0_iter5_reg;
        din_exp_reg_1219_pp0_iter7_reg <= din_exp_reg_1219_pp0_iter6_reg;
        din_sig_reg_1226 <= din_sig_fu_320_p1;
        din_sig_reg_1226_pp0_iter1_reg <= din_sig_reg_1226;
        din_sign_reg_1213 <= data_fu_300_p1[32'd31];
        din_sign_reg_1213_pp0_iter1_reg <= din_sign_reg_1213;
        din_sign_reg_1213_pp0_iter2_reg <= din_sign_reg_1213_pp0_iter1_reg;
        din_sign_reg_1213_pp0_iter3_reg <= din_sign_reg_1213_pp0_iter2_reg;
        din_sign_reg_1213_pp0_iter4_reg <= din_sign_reg_1213_pp0_iter3_reg;
        din_sign_reg_1213_pp0_iter5_reg <= din_sign_reg_1213_pp0_iter4_reg;
        din_sign_reg_1213_pp0_iter6_reg <= din_sign_reg_1213_pp0_iter5_reg;
        din_sign_reg_1213_pp0_iter7_reg <= din_sign_reg_1213_pp0_iter6_reg;
        do_cos_read_reg_1205 <= do_cos_int_reg;
        do_cos_read_reg_1205_pp0_iter10_reg <= do_cos_read_reg_1205_pp0_iter9_reg;
        do_cos_read_reg_1205_pp0_iter11_reg <= do_cos_read_reg_1205_pp0_iter10_reg;
        do_cos_read_reg_1205_pp0_iter12_reg <= do_cos_read_reg_1205_pp0_iter11_reg;
        do_cos_read_reg_1205_pp0_iter13_reg <= do_cos_read_reg_1205_pp0_iter12_reg;
        do_cos_read_reg_1205_pp0_iter14_reg <= do_cos_read_reg_1205_pp0_iter13_reg;
        do_cos_read_reg_1205_pp0_iter15_reg <= do_cos_read_reg_1205_pp0_iter14_reg;
        do_cos_read_reg_1205_pp0_iter16_reg <= do_cos_read_reg_1205_pp0_iter15_reg;
        do_cos_read_reg_1205_pp0_iter1_reg <= do_cos_read_reg_1205;
        do_cos_read_reg_1205_pp0_iter2_reg <= do_cos_read_reg_1205_pp0_iter1_reg;
        do_cos_read_reg_1205_pp0_iter3_reg <= do_cos_read_reg_1205_pp0_iter2_reg;
        do_cos_read_reg_1205_pp0_iter4_reg <= do_cos_read_reg_1205_pp0_iter3_reg;
        do_cos_read_reg_1205_pp0_iter5_reg <= do_cos_read_reg_1205_pp0_iter4_reg;
        do_cos_read_reg_1205_pp0_iter6_reg <= do_cos_read_reg_1205_pp0_iter5_reg;
        do_cos_read_reg_1205_pp0_iter7_reg <= do_cos_read_reg_1205_pp0_iter6_reg;
        do_cos_read_reg_1205_pp0_iter8_reg <= do_cos_read_reg_1205_pp0_iter7_reg;
        do_cos_read_reg_1205_pp0_iter9_reg <= do_cos_read_reg_1205_pp0_iter8_reg;
        icmp_ln271_1_reg_1258 <= icmp_ln271_1_fu_392_p2;
        icmp_ln271_1_reg_1258_pp0_iter3_reg <= icmp_ln271_1_reg_1258;
        icmp_ln271_1_reg_1258_pp0_iter4_reg <= icmp_ln271_1_reg_1258_pp0_iter3_reg;
        icmp_ln271_1_reg_1258_pp0_iter5_reg <= icmp_ln271_1_reg_1258_pp0_iter4_reg;
        icmp_ln271_1_reg_1258_pp0_iter6_reg <= icmp_ln271_1_reg_1258_pp0_iter5_reg;
        icmp_ln271_1_reg_1258_pp0_iter7_reg <= icmp_ln271_1_reg_1258_pp0_iter6_reg;
        icmp_ln282_reg_1336 <= icmp_ln282_fu_752_p2;
        icmp_ln282_reg_1336_pp0_iter10_reg <= icmp_ln282_reg_1336_pp0_iter9_reg;
        icmp_ln282_reg_1336_pp0_iter11_reg <= icmp_ln282_reg_1336_pp0_iter10_reg;
        icmp_ln282_reg_1336_pp0_iter12_reg <= icmp_ln282_reg_1336_pp0_iter11_reg;
        icmp_ln282_reg_1336_pp0_iter13_reg <= icmp_ln282_reg_1336_pp0_iter12_reg;
        icmp_ln282_reg_1336_pp0_iter14_reg <= icmp_ln282_reg_1336_pp0_iter13_reg;
        icmp_ln282_reg_1336_pp0_iter15_reg <= icmp_ln282_reg_1336_pp0_iter14_reg;
        icmp_ln282_reg_1336_pp0_iter16_reg <= icmp_ln282_reg_1336_pp0_iter15_reg;
        icmp_ln282_reg_1336_pp0_iter9_reg <= icmp_ln282_reg_1336;
        icmp_ln292_reg_1470 <= icmp_ln292_fu_1042_p2;
        icmp_ln306_reg_1476 <= icmp_ln306_fu_1048_p2;
        in_shift_1_reg_1464 <= in_shift_1_fu_1037_p2;
        k_reg_1274 <= k_fu_417_p3;
        result_reg_1433 <= {{grp_fu_292_p2[57:29]}};
        results_sign_3_reg_1343 <= results_sign_3_fu_769_p3;
        results_sign_3_reg_1343_pp0_iter10_reg <= results_sign_3_reg_1343_pp0_iter9_reg;
        results_sign_3_reg_1343_pp0_iter11_reg <= results_sign_3_reg_1343_pp0_iter10_reg;
        results_sign_3_reg_1343_pp0_iter12_reg <= results_sign_3_reg_1343_pp0_iter11_reg;
        results_sign_3_reg_1343_pp0_iter13_reg <= results_sign_3_reg_1343_pp0_iter12_reg;
        results_sign_3_reg_1343_pp0_iter14_reg <= results_sign_3_reg_1343_pp0_iter13_reg;
        results_sign_3_reg_1343_pp0_iter15_reg <= results_sign_3_reg_1343_pp0_iter14_reg;
        results_sign_3_reg_1343_pp0_iter16_reg <= results_sign_3_reg_1343_pp0_iter15_reg;
        results_sign_3_reg_1343_pp0_iter9_reg <= results_sign_3_reg_1343;
        second_order_float_sin_cos_K1_load_reg_1398 <= second_order_float_sin_cos_K1_q0;
        second_order_float_sin_cos_K2_load_reg_1403 <= second_order_float_sin_cos_K2_q0;
        sin_basis_reg_1325 <= sin_basis_fu_568_p3;
        sin_basis_reg_1325_pp0_iter9_reg <= sin_basis_reg_1325;
        sub_ln506_reg_1314 <= sub_ln506_fu_551_p2;
        t1_reg_1393 <= {{second_order_float_sin_cos_K0_q0[29:1]}};
        t1_reg_1393_pp0_iter12_reg <= t1_reg_1393;
        tmp_1_reg_1363 <= {{select_ln506_1_fu_801_p3[28:22]}};
        tmp_3_reg_1438 <= {{grp_fu_292_p2[57:42]}};
        tmp_4_reg_1443 <= {{grp_fu_292_p2[41:29]}};
        tmp_7_reg_1284 <= {{Mx_bits_3_fu_432_p3[57:29]}};
        tmp_reg_1308 <= Ex_1_fu_537_p2[32'd7];
        tmp_s_reg_1289 <= tmp_s_fu_447_p19;
        trunc_ln281_1_reg_1458 <= trunc_ln281_1_fu_1033_p1;
        trunc_ln281_reg_1453 <= trunc_ln281_fu_1017_p1;
        trunc_ln2_reg_1408 <= {{mul_ln29_fu_288_p2[44:23]}};
        trunc_ln379_reg_1243 <= trunc_ln379_fu_359_p1;
        trunc_ln3_reg_1413 <= {{mul_ln30_fu_910_p2[29:16]}};
        trunc_ln5_reg_1448 <= {{grp_fu_292_p2[56:29]}};
        trunc_ln_reg_1269 <= {{grp_fu_296_p2[79:77]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ref_4oPi_table_100_ce0_local = 1'b1;
    end else begin
        ref_4oPi_table_100_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        second_order_float_sin_cos_K0_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        second_order_float_sin_cos_K1_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        second_order_float_sin_cos_K2_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K2_ce0_local = 1'b0;
    end
end

assign A_fu_844_p3 = {{sin_basis_reg_1325_pp0_iter9_reg}, {tmp_1_reg_1363}};

assign B_fu_808_p1 = select_ln506_1_fu_801_p3[21:0];

assign Ex_1_fu_537_p2 = (select_ln453_fu_492_p3 - trunc_ln505_fu_533_p1);

assign Ex_2_fu_818_p3 = ((cos_basis_reg_1319[0:0] == 1'b1) ? 8'd0 : Ex_1_reg_1302);

assign Ex_fu_487_p2 = ($signed(din_exp_reg_1219_pp0_iter7_reg) + $signed(8'd131));

assign Mx_1_fu_812_p3 = ((cos_basis_reg_1319[0:0] == 1'b1) ? 29'd536870911 : Mx_reg_1296);

assign Mx_bits_1_fu_427_p2 = (58'd0 - Mx_bits_reg_1263);

assign Mx_bits_3_fu_432_p3 = ((trunc_ln491_fu_423_p1[0:0] == 1'b1) ? Mx_bits_1_fu_427_p2 : Mx_bits_reg_1263);

assign Mx_zeros_fu_506_p1 = {{tmp_7_reg_1284}, {1'd1}};

assign X_fu_380_p3 = {{1'd1}, {din_sig_reg_1226_pp0_iter1_reg}};

assign add_ln300_fu_1081_p2 = ($signed(sext_ln252_fu_1053_p1) + $signed(9'd127));

assign add_ln32_1_fu_941_p2 = ($signed(add_ln32_fu_932_p2) + $signed(sext_ln32_2_fu_938_p1));

assign add_ln32_fu_932_p2 = ($signed(sext_ln32_fu_926_p1) + $signed(sext_ln32_1_fu_929_p1));

assign add_ln376_fu_330_p2 = ($signed(din_exp_fu_312_p3) + $signed(8'd194));

assign addr_fu_336_p3 = ((closepath_fu_324_p2[0:0] == 1'b1) ? 8'd63 : add_ln376_fu_330_p2);

assign and_ln271_fu_737_p2 = (icmp_ln271_fu_732_p2 & icmp_ln271_1_reg_1258_pp0_iter7_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = t_2_fu_1192_p4;

assign c_1_fu_1025_p1 = {{tmp_4_reg_1443}, {19'd262144}};

assign c_fu_1009_p1 = {{tmp_3_reg_1438}, {16'd32768}};

assign closepath_fu_324_p2 = ((din_exp_fu_312_p3 < 8'd126) ? 1'b1 : 1'b0);

assign cos_basis_fu_562_p3 = ((do_cos_read_reg_1205_pp0_iter7_reg[0:0] == 1'b1) ? xor_ln242_fu_557_p2 : tmp_s_reg_1289);

assign data_fu_300_p1 = t_in_int_reg;

assign din_exp_fu_312_p3 = {{data_fu_300_p1[30:23]}};

assign din_sig_fu_320_p1 = data_fu_300_p1[22:0];

assign empty_59_fu_1129_p3 = ((icmp_ln292_reg_1470[0:0] == 1'b1) ? tmp_6_fu_1110_p4 : tmp_9_fu_1120_p4);

assign empty_fu_1106_p1 = newexp_fu_1087_p2[7:0];

assign grp_fu_292_p1 = grp_fu_292_p10;

assign grp_fu_292_p10 = Mx_1_reg_1353_pp0_iter13_reg;

assign grp_fu_296_p1 = grp_fu_296_p10;

assign grp_fu_296_p10 = X_fu_380_p3;

assign icmp_ln271_1_fu_392_p2 = ((din_sig_reg_1226_pp0_iter1_reg == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_732_p2 = ((din_exp_reg_1219_pp0_iter7_reg == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln282_fu_752_p2 = ((din_exp_reg_1219_pp0_iter7_reg == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln292_fu_1042_p2 = ((trunc_ln281_fu_1017_p1 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln306_fu_1048_p2 = ((result_reg_1433 == 29'd0) ? 1'b1 : 1'b0);

assign in_shift_1_fu_1037_p2 = trunc_ln5_reg_1448 << zext_ln281_fu_1021_p1;

assign in_shift_2_fu_1066_p2 = in_shift_1_reg_1464 << zext_ln281_1_fu_1056_p1;

assign index_fu_574_p3 = {{din_sign_reg_1213_pp0_iter7_reg}, {k_reg_1274}};

assign k_fu_417_p3 = ((closepath_reg_1232_pp0_iter6_reg[0:0] == 1'b1) ? 3'd0 : trunc_ln_reg_1269);

assign lshr_ln506_fu_789_p2 = zext_ln506_fu_786_p1 >> zext_ln506_1_fu_782_p1;

assign lshr_ln_fu_344_p4 = {{addr_fu_336_p3[7:4]}};

assign mul_ln23_fu_860_p0 = zext_ln23_fu_857_p1;

assign mul_ln23_fu_860_p1 = zext_ln23_fu_857_p1;

assign mul_ln29_fu_288_p1 = mul_ln29_fu_288_p10;

assign mul_ln29_fu_288_p10 = B_reg_1348_pp0_iter11_reg;

assign mul_ln30_fu_910_p0 = mul_ln30_fu_910_p00;

assign mul_ln30_fu_910_p00 = B_squared_reg_1388;

assign newexp_fu_1087_p2 = (add_ln300_fu_1081_p2 - zext_ln286_fu_1077_p1);

assign or_ln282_fu_1150_p2 = (or_ln306_fu_1101_p2 | icmp_ln282_reg_1336_pp0_iter16_reg);

assign or_ln306_fu_1101_p2 = (tmp_2_fu_1093_p3 | icmp_ln306_reg_1476);

assign ref_4oPi_table_100_address0 = zext_ln378_fu_354_p1;

assign results_exp_1_fu_1178_p3 = ((and_ln271_reg_1330_pp0_iter16_reg[0:0] == 1'b1) ? select_ln259_fu_1136_p3 : results_exp_fu_1155_p3);

assign results_exp_fu_1155_p3 = ((or_ln282_fu_1150_p2[0:0] == 1'b1) ? select_ln282_fu_1143_p3 : empty_fu_1106_p1);

assign results_sig_1_fu_1185_p3 = ((and_ln271_reg_1330_pp0_iter16_reg[0:0] == 1'b1) ? 23'd0 : results_sig_fu_1170_p3);

assign results_sig_fu_1170_p3 = ((or_ln282_fu_1150_p2[0:0] == 1'b1) ? select_ln282_2_fu_1163_p3 : empty_59_fu_1129_p3);

assign results_sign_2_fu_747_p2 = (xor_ln278_fu_742_p2 & din_sign_reg_1213_pp0_iter7_reg);

assign results_sign_3_fu_769_p3 = ((and_ln271_fu_737_p2[0:0] == 1'b1) ? results_sign_2_fu_747_p2 : results_sign_4_fu_763_p2);

assign results_sign_4_fu_763_p2 = (xor_ln282_fu_757_p2 & results_sign_fu_724_p3);

assign results_sign_fu_724_p3 = ((cos_basis_fu_562_p3[0:0] == 1'b1) ? tmp_8_fu_580_p35 : tmp_5_fu_652_p35);

assign second_order_float_sin_cos_K0_address0 = zext_ln28_fu_850_p1;

assign second_order_float_sin_cos_K1_address0 = zext_ln28_fu_850_p1;

assign second_order_float_sin_cos_K2_address0 = zext_ln28_fu_850_p1;

assign select_ln259_fu_1136_p3 = ((do_cos_read_reg_1205_pp0_iter16_reg[0:0] == 1'b1) ? 8'd127 : 8'd0);

assign select_ln282_2_fu_1163_p3 = ((icmp_ln282_reg_1336_pp0_iter16_reg[0:0] == 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln282_fu_1143_p3 = ((icmp_ln282_reg_1336_pp0_iter16_reg[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln453_fu_492_p3 = ((closepath_reg_1232_pp0_iter7_reg[0:0] == 1'b1) ? Ex_fu_487_p2 : 8'd0);

assign select_ln506_1_fu_801_p3 = ((tmp_reg_1308[0:0] == 1'b1) ? lshr_ln506_fu_789_p2 : shl_ln506_fu_795_p2);

assign select_ln506_fu_777_p3 = ((tmp_reg_1308[0:0] == 1'b1) ? sub_ln506_reg_1314 : Ex_1_reg_1302);

assign sext_ln252_fu_1053_p1 = $signed(Ex_2_reg_1358_pp0_iter16_reg);

assign sext_ln32_1_fu_929_p1 = $signed(trunc_ln2_reg_1408);

assign sext_ln32_2_fu_938_p1 = $signed(trunc_ln3_reg_1413);

assign sext_ln32_fu_926_p1 = $signed(t1_reg_1393_pp0_iter12_reg);

assign shift_1_fu_1059_p3 = {{1'd1}, {trunc_ln281_1_reg_1458}};

assign shift_2_fu_1071_p3 = ((icmp_ln292_reg_1470[0:0] == 1'b1) ? shift_1_fu_1059_p3 : trunc_ln281_reg_1453);

assign shl_ln379_fu_366_p2 = ref_4oPi_table_100_q0 << zext_ln379_fu_363_p1;

assign shl_ln504_fu_518_p2 = Mx_bits_3_reg_1279 << zext_ln504_fu_514_p1;

assign shl_ln506_fu_795_p2 = zext_ln506_fu_786_p1 << zext_ln506_1_fu_782_p1;

assign sin_basis_fu_568_p3 = ((do_cos_read_reg_1205_pp0_iter7_reg[0:0] == 1'b1) ? tmp_s_reg_1289 : xor_ln242_fu_557_p2);

assign sub_ln506_fu_551_p2 = (8'd0 - Ex_1_fu_537_p2);

assign t_2_fu_1192_p4 = {{{results_sign_3_reg_1343_pp0_iter16_reg}, {results_exp_1_fu_1178_p3}}, {results_sig_1_fu_1185_p3}};

assign tmp_2_fu_1093_p3 = newexp_fu_1087_p2[32'd8];

assign tmp_5_fu_652_p33 = 'bx;

assign tmp_6_fu_1110_p4 = {{in_shift_2_fu_1066_p2[27:5]}};

assign tmp_8_fu_580_p33 = 'bx;

assign tmp_9_fu_1120_p4 = {{in_shift_1_reg_1464[27:5]}};

assign tmp_s_fu_447_p17 = 'bx;

assign trunc_ln281_1_fu_1033_p1 = c_1_fu_1025_p3[3:0];

assign trunc_ln281_fu_1017_p1 = c_fu_1009_p3[4:0];

assign trunc_ln379_fu_359_p1 = addr_fu_336_p3[3:0];

assign trunc_ln491_fu_423_p1 = k_fu_417_p3[0:0];

assign trunc_ln505_fu_533_p1 = Mx_zeros_fu_506_p3[7:0];

assign xor_ln242_fu_557_p2 = (tmp_s_reg_1289 ^ 1'd1);

assign xor_ln278_fu_742_p2 = (do_cos_read_reg_1205_pp0_iter7_reg ^ 1'd1);

assign xor_ln282_fu_757_p2 = (icmp_ln282_fu_752_p2 ^ 1'd1);

assign zext_ln23_fu_857_p1 = B_trunc_reg_1368_pp0_iter10_reg;

assign zext_ln281_1_fu_1056_p1 = trunc_ln281_1_reg_1458;

assign zext_ln281_fu_1021_p1 = trunc_ln281_fu_1017_p1;

assign zext_ln286_fu_1077_p1 = shift_2_fu_1071_p3;

assign zext_ln28_fu_850_p1 = A_fu_844_p3;

assign zext_ln378_fu_354_p1 = lshr_ln_fu_344_p4;

assign zext_ln379_fu_363_p1 = trunc_ln379_reg_1243;

assign zext_ln504_fu_514_p1 = Mx_zeros_fu_506_p3;

assign zext_ln506_1_fu_782_p1 = select_ln506_fu_777_p3;

assign zext_ln506_fu_786_p1 = Mx_reg_1296;

endmodule //enhanced_correlator_sin_or_cos_float_s
