-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity enhanced_correlator_sin_or_cos_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    t_in : IN STD_LOGIC_VECTOR (31 downto 0);
    do_cos : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of enhanced_correlator_sin_or_cos_float_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_C2 : STD_LOGIC_VECTOR (7 downto 0) := "11000010";
    constant ap_const_lv8_3F : STD_LOGIC_VECTOR (7 downto 0) := "00111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv58_0 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_83 : STD_LOGIC_VECTOR (7 downto 0) := "10000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv29_1FFFFFFF : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111111111111111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv19_40000 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv9_7F : STD_LOGIC_VECTOR (8 downto 0) := "001111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv23_7FFFFF : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111111111";

attribute shreg_extract : string;
    signal ref_4oPi_table_100_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ref_4oPi_table_100_q0 : STD_LOGIC_VECTOR (99 downto 0);
    signal second_order_float_sin_cos_K0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K0_q0 : STD_LOGIC_VECTOR (29 downto 0);
    signal second_order_float_sin_cos_K1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K1_q0 : STD_LOGIC_VECTOR (22 downto 0);
    signal second_order_float_sin_cos_K2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_sin_cos_K2_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal do_cos_read_reg_1205 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal do_cos_read_reg_1205_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal do_cos_read_reg_1205_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213 : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_1213_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_exp_fu_312_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_exp_reg_1219_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal din_sig_fu_320_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal din_sig_reg_1226 : STD_LOGIC_VECTOR (22 downto 0);
    signal din_sig_reg_1226_pp0_iter1_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal closepath_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232 : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1232_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln379_fu_359_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln379_reg_1243 : STD_LOGIC_VECTOR (3 downto 0);
    signal Med_reg_1248 : STD_LOGIC_VECTOR (79 downto 0);
    signal icmp_ln271_1_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1258 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1258_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1258_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1258_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1258_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_1_reg_1258_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_bits_reg_1263 : STD_LOGIC_VECTOR (57 downto 0);
    signal trunc_ln_reg_1269 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_fu_417_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_reg_1274 : STD_LOGIC_VECTOR (2 downto 0);
    signal Mx_bits_3_fu_432_p3 : STD_LOGIC_VECTOR (57 downto 0);
    signal Mx_bits_3_reg_1279 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_7_reg_1284 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_s_fu_447_p19 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1289 : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_reg_1296 : STD_LOGIC_VECTOR (28 downto 0);
    signal Ex_1_fu_537_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_1_reg_1302 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln506_fu_551_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln506_reg_1314 : STD_LOGIC_VECTOR (7 downto 0);
    signal cos_basis_fu_562_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1319 : STD_LOGIC_VECTOR (0 downto 0);
    signal sin_basis_fu_568_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sin_basis_reg_1325 : STD_LOGIC_VECTOR (0 downto 0);
    signal sin_basis_reg_1325_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln271_reg_1330_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln282_reg_1336_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_fu_769_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_3_reg_1343_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal B_fu_808_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal B_reg_1348 : STD_LOGIC_VECTOR (21 downto 0);
    signal B_reg_1348_pp0_iter10_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal B_reg_1348_pp0_iter11_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal Mx_1_fu_812_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_1_reg_1353 : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_1_reg_1353_pp0_iter10_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_1_reg_1353_pp0_iter11_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_1_reg_1353_pp0_iter12_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_1_reg_1353_pp0_iter13_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal Ex_2_fu_818_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358 : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358_pp0_iter10_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358_pp0_iter11_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358_pp0_iter12_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358_pp0_iter13_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358_pp0_iter14_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358_pp0_iter15_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_2_reg_1358_pp0_iter16_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_1363 : STD_LOGIC_VECTOR (6 downto 0);
    signal B_trunc_reg_1368 : STD_LOGIC_VECTOR (14 downto 0);
    signal B_trunc_reg_1368_pp0_iter10_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal B_squared_reg_1388 : STD_LOGIC_VECTOR (14 downto 0);
    signal t1_reg_1393 : STD_LOGIC_VECTOR (28 downto 0);
    signal t1_reg_1393_pp0_iter12_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal second_order_float_sin_cos_K1_load_reg_1398 : STD_LOGIC_VECTOR (22 downto 0);
    signal second_order_float_sin_cos_K2_load_reg_1403 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln2_reg_1408 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln3_reg_1413 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln32_1_fu_941_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln32_1_reg_1418 : STD_LOGIC_VECTOR (29 downto 0);
    signal result_reg_1433 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_3_reg_1438 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_reg_1443 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln5_reg_1448 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln281_fu_1017_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln281_reg_1453 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln281_1_fu_1033_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln281_1_reg_1458 : STD_LOGIC_VECTOR (3 downto 0);
    signal in_shift_1_fu_1037_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal in_shift_1_reg_1464 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln292_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln292_reg_1470 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln306_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln306_reg_1476 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln378_fu_354_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln28_fu_850_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ref_4oPi_table_100_ce0_local : STD_LOGIC;
    signal second_order_float_sin_cos_K0_ce0_local : STD_LOGIC;
    signal second_order_float_sin_cos_K1_ce0_local : STD_LOGIC;
    signal second_order_float_sin_cos_K2_ce0_local : STD_LOGIC;
    signal mul_ln29_fu_288_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_292_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_296_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal data_fu_300_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln376_fu_330_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal addr_fu_336_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln_fu_344_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln379_fu_363_p1 : STD_LOGIC_VECTOR (99 downto 0);
    signal shl_ln379_fu_366_p2 : STD_LOGIC_VECTOR (99 downto 0);
    signal X_fu_380_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_296_p2 : STD_LOGIC_VECTOR (79 downto 0);
    signal trunc_ln491_fu_423_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_bits_1_fu_427_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_s_fu_447_p17 : STD_LOGIC_VECTOR (0 downto 0);
    signal Ex_fu_487_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Mx_zeros_fu_506_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal Mx_zeros_fu_506_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln504_fu_514_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal shl_ln504_fu_518_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal select_ln453_fu_492_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln505_fu_533_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln242_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_580_p33 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_fu_574_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p33 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_580_p35 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_652_p35 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln271_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln278_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_fu_724_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln282_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_2_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal results_sign_4_fu_763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln506_fu_777_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln506_fu_786_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln506_1_fu_782_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln506_fu_789_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln506_fu_795_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln506_1_fu_801_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_fu_844_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln23_fu_860_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln23_fu_857_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln23_fu_860_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln23_fu_860_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln29_fu_288_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln30_fu_910_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln30_fu_910_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_fu_926_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_1_fu_929_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln32_fu_932_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln32_2_fu_938_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_292_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal c_fu_1009_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_fu_1009_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_fu_1025_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_fu_1025_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln281_fu_1021_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln281_1_fu_1056_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal shift_1_fu_1059_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shift_2_fu_1071_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln252_fu_1053_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln300_fu_1081_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln286_fu_1077_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal newexp_fu_1087_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_1093_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_shift_2_fu_1066_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_6_fu_1110_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_9_fu_1120_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln306_fu_1101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln282_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln282_fu_1143_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_1106_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln282_2_fu_1163_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal empty_59_fu_1129_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal select_ln259_fu_1136_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_exp_fu_1155_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_sig_fu_1170_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal results_exp_1_fu_1178_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal results_sig_1_fu_1185_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_2_fu_1192_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_in_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal do_cos_int_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_292_p10 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_fu_296_p10 : STD_LOGIC_VECTOR (79 downto 0);
    signal mul_ln29_fu_288_p10 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln30_fu_910_p00 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_s_fu_447_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_447_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_447_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_447_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_447_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_447_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_447_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_447_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal Mx_zeros_fu_506_p0 : STD_LOGIC_VECTOR (29 downto 0);
    signal Mx_zeros_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_580_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_580_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_652_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_fu_1009_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_1_fu_1025_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_fu_1025_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component enhanced_correlator_mul_23s_22ns_45_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        dout : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component enhanced_correlator_mul_30s_29ns_58_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component enhanced_correlator_mul_80s_24ns_80_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (79 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (79 downto 0) );
    end component;


    component enhanced_correlator_sparsemux_17_3_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component enhanced_correlator_ctlz_30_30_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (29 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component enhanced_correlator_sparsemux_33_4_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        din9 : IN STD_LOGIC_VECTOR (0 downto 0);
        din10 : IN STD_LOGIC_VECTOR (0 downto 0);
        din11 : IN STD_LOGIC_VECTOR (0 downto 0);
        din12 : IN STD_LOGIC_VECTOR (0 downto 0);
        din13 : IN STD_LOGIC_VECTOR (0 downto 0);
        din14 : IN STD_LOGIC_VECTOR (0 downto 0);
        din15 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component enhanced_correlator_mul_15ns_15ns_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component enhanced_correlator_mul_15ns_15s_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component enhanced_correlator_ctlz_32_32_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component enhanced_correlator_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (99 downto 0) );
    end component;


    component enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    ref_4oPi_table_100_U : component enhanced_correlator_sin_or_cos_float_s_ref_4oPi_table_100_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 100,
        AddressRange => 13,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ref_4oPi_table_100_address0,
        ce0 => ref_4oPi_table_100_ce0_local,
        q0 => ref_4oPi_table_100_q0);

    second_order_float_sin_cos_K0_U : component enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 30,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K0_address0,
        ce0 => second_order_float_sin_cos_K0_ce0_local,
        q0 => second_order_float_sin_cos_K0_q0);

    second_order_float_sin_cos_K1_U : component enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 23,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K1_address0,
        ce0 => second_order_float_sin_cos_K1_ce0_local,
        q0 => second_order_float_sin_cos_K1_q0);

    second_order_float_sin_cos_K2_U : component enhanced_correlator_sin_or_cos_float_s_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R
    generic map (
        DataWidth => 15,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_sin_cos_K2_address0,
        ce0 => second_order_float_sin_cos_K2_ce0_local,
        q0 => second_order_float_sin_cos_K2_q0);

    mul_23s_22ns_45_1_1_U1 : component enhanced_correlator_mul_23s_22ns_45_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 23,
        din1_WIDTH => 22,
        dout_WIDTH => 45)
    port map (
        din0 => second_order_float_sin_cos_K1_load_reg_1398,
        din1 => mul_ln29_fu_288_p1,
        dout => mul_ln29_fu_288_p2);

    mul_30s_29ns_58_2_1_U2 : component enhanced_correlator_mul_30s_29ns_58_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 30,
        din1_WIDTH => 29,
        dout_WIDTH => 58)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_ln32_1_reg_1418,
        din1 => grp_fu_292_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_292_p2);

    mul_80s_24ns_80_5_1_U3 : component enhanced_correlator_mul_80s_24ns_80_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 80,
        din1_WIDTH => 24,
        dout_WIDTH => 80)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Med_reg_1248,
        din1 => grp_fu_296_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_296_p2);

    sparsemux_17_3_1_1_1_U4 : component enhanced_correlator_sparsemux_17_3_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 1,
        CASE1 => "001",
        din1_WIDTH => 1,
        CASE2 => "010",
        din2_WIDTH => 1,
        CASE3 => "011",
        din3_WIDTH => 1,
        CASE4 => "100",
        din4_WIDTH => 1,
        CASE5 => "101",
        din5_WIDTH => 1,
        CASE6 => "110",
        din6_WIDTH => 1,
        CASE7 => "111",
        din7_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 3,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_0,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        def => tmp_s_fu_447_p17,
        sel => k_fu_417_p3,
        dout => tmp_s_fu_447_p19);

    ctlz_30_30_1_1_U5 : component enhanced_correlator_ctlz_30_30_1_1
    generic map (
        din_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        din => Mx_zeros_fu_506_p1,
        dout => Mx_zeros_fu_506_p3);

    sparsemux_33_4_1_1_1_U6 : component enhanced_correlator_sparsemux_33_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        CASE9 => "1001",
        din9_WIDTH => 1,
        CASE10 => "1010",
        din10_WIDTH => 1,
        CASE11 => "1011",
        din11_WIDTH => 1,
        CASE12 => "1100",
        din12_WIDTH => 1,
        CASE13 => "1101",
        din13_WIDTH => 1,
        CASE14 => "1110",
        din14_WIDTH => 1,
        CASE15 => "1111",
        din15_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_1,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        din8 => ap_const_lv1_0,
        din9 => ap_const_lv1_1,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_1,
        din13 => ap_const_lv1_0,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        def => tmp_8_fu_580_p33,
        sel => index_fu_574_p3,
        dout => tmp_8_fu_580_p35);

    sparsemux_33_4_1_1_1_U7 : component enhanced_correlator_sparsemux_33_4_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 1,
        CASE1 => "0001",
        din1_WIDTH => 1,
        CASE2 => "0010",
        din2_WIDTH => 1,
        CASE3 => "0011",
        din3_WIDTH => 1,
        CASE4 => "0100",
        din4_WIDTH => 1,
        CASE5 => "0101",
        din5_WIDTH => 1,
        CASE6 => "0110",
        din6_WIDTH => 1,
        CASE7 => "0111",
        din7_WIDTH => 1,
        CASE8 => "1000",
        din8_WIDTH => 1,
        CASE9 => "1001",
        din9_WIDTH => 1,
        CASE10 => "1010",
        din10_WIDTH => 1,
        CASE11 => "1011",
        din11_WIDTH => 1,
        CASE12 => "1100",
        din12_WIDTH => 1,
        CASE13 => "1101",
        din13_WIDTH => 1,
        CASE14 => "1110",
        din14_WIDTH => 1,
        CASE15 => "1111",
        din15_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_0,
        din7 => ap_const_lv1_1,
        din8 => ap_const_lv1_1,
        din9 => ap_const_lv1_0,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_0,
        din13 => ap_const_lv1_1,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        def => tmp_5_fu_652_p33,
        sel => index_fu_574_p3,
        dout => tmp_5_fu_652_p35);

    mul_15ns_15ns_30_1_1_U8 : component enhanced_correlator_mul_15ns_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln23_fu_860_p0,
        din1 => mul_ln23_fu_860_p1,
        dout => mul_ln23_fu_860_p2);

    mul_15ns_15s_30_1_1_U9 : component enhanced_correlator_mul_15ns_15s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln30_fu_910_p0,
        din1 => second_order_float_sin_cos_K2_load_reg_1403,
        dout => mul_ln30_fu_910_p2);

    ctlz_32_32_1_1_U10 : component enhanced_correlator_ctlz_32_32_1_1
    generic map (
        din_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din => c_fu_1009_p1,
        dout => c_fu_1009_p3);

    ctlz_32_32_1_1_U11 : component enhanced_correlator_ctlz_32_32_1_1
    generic map (
        din_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din => c_1_fu_1025_p1,
        dout => c_1_fu_1025_p3);





    do_cos_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            do_cos_int_reg <= do_cos;
        end if;
    end process;

    t_in_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            t_in_int_reg <= t_in;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                B_reg_1348 <= B_fu_808_p1;
                B_reg_1348_pp0_iter10_reg <= B_reg_1348;
                B_reg_1348_pp0_iter11_reg <= B_reg_1348_pp0_iter10_reg;
                B_squared_reg_1388 <= mul_ln23_fu_860_p2(29 downto 15);
                B_trunc_reg_1368 <= select_ln506_1_fu_801_p3(21 downto 7);
                B_trunc_reg_1368_pp0_iter10_reg <= B_trunc_reg_1368;
                Ex_1_reg_1302 <= Ex_1_fu_537_p2;
                Ex_2_reg_1358 <= Ex_2_fu_818_p3;
                Ex_2_reg_1358_pp0_iter10_reg <= Ex_2_reg_1358;
                Ex_2_reg_1358_pp0_iter11_reg <= Ex_2_reg_1358_pp0_iter10_reg;
                Ex_2_reg_1358_pp0_iter12_reg <= Ex_2_reg_1358_pp0_iter11_reg;
                Ex_2_reg_1358_pp0_iter13_reg <= Ex_2_reg_1358_pp0_iter12_reg;
                Ex_2_reg_1358_pp0_iter14_reg <= Ex_2_reg_1358_pp0_iter13_reg;
                Ex_2_reg_1358_pp0_iter15_reg <= Ex_2_reg_1358_pp0_iter14_reg;
                Ex_2_reg_1358_pp0_iter16_reg <= Ex_2_reg_1358_pp0_iter15_reg;
                Med_reg_1248 <= shl_ln379_fu_366_p2(99 downto 20);
                Mx_1_reg_1353 <= Mx_1_fu_812_p3;
                Mx_1_reg_1353_pp0_iter10_reg <= Mx_1_reg_1353;
                Mx_1_reg_1353_pp0_iter11_reg <= Mx_1_reg_1353_pp0_iter10_reg;
                Mx_1_reg_1353_pp0_iter12_reg <= Mx_1_reg_1353_pp0_iter11_reg;
                Mx_1_reg_1353_pp0_iter13_reg <= Mx_1_reg_1353_pp0_iter12_reg;
                Mx_bits_3_reg_1279 <= Mx_bits_3_fu_432_p3;
                Mx_bits_reg_1263 <= grp_fu_296_p2(76 downto 19);
                Mx_reg_1296 <= shl_ln504_fu_518_p2(57 downto 29);
                add_ln32_1_reg_1418 <= add_ln32_1_fu_941_p2;
                and_ln271_reg_1330 <= and_ln271_fu_737_p2;
                and_ln271_reg_1330_pp0_iter10_reg <= and_ln271_reg_1330_pp0_iter9_reg;
                and_ln271_reg_1330_pp0_iter11_reg <= and_ln271_reg_1330_pp0_iter10_reg;
                and_ln271_reg_1330_pp0_iter12_reg <= and_ln271_reg_1330_pp0_iter11_reg;
                and_ln271_reg_1330_pp0_iter13_reg <= and_ln271_reg_1330_pp0_iter12_reg;
                and_ln271_reg_1330_pp0_iter14_reg <= and_ln271_reg_1330_pp0_iter13_reg;
                and_ln271_reg_1330_pp0_iter15_reg <= and_ln271_reg_1330_pp0_iter14_reg;
                and_ln271_reg_1330_pp0_iter16_reg <= and_ln271_reg_1330_pp0_iter15_reg;
                and_ln271_reg_1330_pp0_iter9_reg <= and_ln271_reg_1330;
                closepath_reg_1232 <= closepath_fu_324_p2;
                closepath_reg_1232_pp0_iter1_reg <= closepath_reg_1232;
                closepath_reg_1232_pp0_iter2_reg <= closepath_reg_1232_pp0_iter1_reg;
                closepath_reg_1232_pp0_iter3_reg <= closepath_reg_1232_pp0_iter2_reg;
                closepath_reg_1232_pp0_iter4_reg <= closepath_reg_1232_pp0_iter3_reg;
                closepath_reg_1232_pp0_iter5_reg <= closepath_reg_1232_pp0_iter4_reg;
                closepath_reg_1232_pp0_iter6_reg <= closepath_reg_1232_pp0_iter5_reg;
                closepath_reg_1232_pp0_iter7_reg <= closepath_reg_1232_pp0_iter6_reg;
                cos_basis_reg_1319 <= cos_basis_fu_562_p3;
                din_exp_reg_1219 <= data_fu_300_p1(30 downto 23);
                din_exp_reg_1219_pp0_iter1_reg <= din_exp_reg_1219;
                din_exp_reg_1219_pp0_iter2_reg <= din_exp_reg_1219_pp0_iter1_reg;
                din_exp_reg_1219_pp0_iter3_reg <= din_exp_reg_1219_pp0_iter2_reg;
                din_exp_reg_1219_pp0_iter4_reg <= din_exp_reg_1219_pp0_iter3_reg;
                din_exp_reg_1219_pp0_iter5_reg <= din_exp_reg_1219_pp0_iter4_reg;
                din_exp_reg_1219_pp0_iter6_reg <= din_exp_reg_1219_pp0_iter5_reg;
                din_exp_reg_1219_pp0_iter7_reg <= din_exp_reg_1219_pp0_iter6_reg;
                din_sig_reg_1226 <= din_sig_fu_320_p1;
                din_sig_reg_1226_pp0_iter1_reg <= din_sig_reg_1226;
                din_sign_reg_1213 <= data_fu_300_p1(31 downto 31);
                din_sign_reg_1213_pp0_iter1_reg <= din_sign_reg_1213;
                din_sign_reg_1213_pp0_iter2_reg <= din_sign_reg_1213_pp0_iter1_reg;
                din_sign_reg_1213_pp0_iter3_reg <= din_sign_reg_1213_pp0_iter2_reg;
                din_sign_reg_1213_pp0_iter4_reg <= din_sign_reg_1213_pp0_iter3_reg;
                din_sign_reg_1213_pp0_iter5_reg <= din_sign_reg_1213_pp0_iter4_reg;
                din_sign_reg_1213_pp0_iter6_reg <= din_sign_reg_1213_pp0_iter5_reg;
                din_sign_reg_1213_pp0_iter7_reg <= din_sign_reg_1213_pp0_iter6_reg;
                do_cos_read_reg_1205 <= do_cos_int_reg;
                do_cos_read_reg_1205_pp0_iter10_reg <= do_cos_read_reg_1205_pp0_iter9_reg;
                do_cos_read_reg_1205_pp0_iter11_reg <= do_cos_read_reg_1205_pp0_iter10_reg;
                do_cos_read_reg_1205_pp0_iter12_reg <= do_cos_read_reg_1205_pp0_iter11_reg;
                do_cos_read_reg_1205_pp0_iter13_reg <= do_cos_read_reg_1205_pp0_iter12_reg;
                do_cos_read_reg_1205_pp0_iter14_reg <= do_cos_read_reg_1205_pp0_iter13_reg;
                do_cos_read_reg_1205_pp0_iter15_reg <= do_cos_read_reg_1205_pp0_iter14_reg;
                do_cos_read_reg_1205_pp0_iter16_reg <= do_cos_read_reg_1205_pp0_iter15_reg;
                do_cos_read_reg_1205_pp0_iter1_reg <= do_cos_read_reg_1205;
                do_cos_read_reg_1205_pp0_iter2_reg <= do_cos_read_reg_1205_pp0_iter1_reg;
                do_cos_read_reg_1205_pp0_iter3_reg <= do_cos_read_reg_1205_pp0_iter2_reg;
                do_cos_read_reg_1205_pp0_iter4_reg <= do_cos_read_reg_1205_pp0_iter3_reg;
                do_cos_read_reg_1205_pp0_iter5_reg <= do_cos_read_reg_1205_pp0_iter4_reg;
                do_cos_read_reg_1205_pp0_iter6_reg <= do_cos_read_reg_1205_pp0_iter5_reg;
                do_cos_read_reg_1205_pp0_iter7_reg <= do_cos_read_reg_1205_pp0_iter6_reg;
                do_cos_read_reg_1205_pp0_iter8_reg <= do_cos_read_reg_1205_pp0_iter7_reg;
                do_cos_read_reg_1205_pp0_iter9_reg <= do_cos_read_reg_1205_pp0_iter8_reg;
                icmp_ln271_1_reg_1258 <= icmp_ln271_1_fu_392_p2;
                icmp_ln271_1_reg_1258_pp0_iter3_reg <= icmp_ln271_1_reg_1258;
                icmp_ln271_1_reg_1258_pp0_iter4_reg <= icmp_ln271_1_reg_1258_pp0_iter3_reg;
                icmp_ln271_1_reg_1258_pp0_iter5_reg <= icmp_ln271_1_reg_1258_pp0_iter4_reg;
                icmp_ln271_1_reg_1258_pp0_iter6_reg <= icmp_ln271_1_reg_1258_pp0_iter5_reg;
                icmp_ln271_1_reg_1258_pp0_iter7_reg <= icmp_ln271_1_reg_1258_pp0_iter6_reg;
                icmp_ln282_reg_1336 <= icmp_ln282_fu_752_p2;
                icmp_ln282_reg_1336_pp0_iter10_reg <= icmp_ln282_reg_1336_pp0_iter9_reg;
                icmp_ln282_reg_1336_pp0_iter11_reg <= icmp_ln282_reg_1336_pp0_iter10_reg;
                icmp_ln282_reg_1336_pp0_iter12_reg <= icmp_ln282_reg_1336_pp0_iter11_reg;
                icmp_ln282_reg_1336_pp0_iter13_reg <= icmp_ln282_reg_1336_pp0_iter12_reg;
                icmp_ln282_reg_1336_pp0_iter14_reg <= icmp_ln282_reg_1336_pp0_iter13_reg;
                icmp_ln282_reg_1336_pp0_iter15_reg <= icmp_ln282_reg_1336_pp0_iter14_reg;
                icmp_ln282_reg_1336_pp0_iter16_reg <= icmp_ln282_reg_1336_pp0_iter15_reg;
                icmp_ln282_reg_1336_pp0_iter9_reg <= icmp_ln282_reg_1336;
                icmp_ln292_reg_1470 <= icmp_ln292_fu_1042_p2;
                icmp_ln306_reg_1476 <= icmp_ln306_fu_1048_p2;
                in_shift_1_reg_1464 <= in_shift_1_fu_1037_p2;
                k_reg_1274 <= k_fu_417_p3;
                result_reg_1433 <= grp_fu_292_p2(57 downto 29);
                results_sign_3_reg_1343 <= results_sign_3_fu_769_p3;
                results_sign_3_reg_1343_pp0_iter10_reg <= results_sign_3_reg_1343_pp0_iter9_reg;
                results_sign_3_reg_1343_pp0_iter11_reg <= results_sign_3_reg_1343_pp0_iter10_reg;
                results_sign_3_reg_1343_pp0_iter12_reg <= results_sign_3_reg_1343_pp0_iter11_reg;
                results_sign_3_reg_1343_pp0_iter13_reg <= results_sign_3_reg_1343_pp0_iter12_reg;
                results_sign_3_reg_1343_pp0_iter14_reg <= results_sign_3_reg_1343_pp0_iter13_reg;
                results_sign_3_reg_1343_pp0_iter15_reg <= results_sign_3_reg_1343_pp0_iter14_reg;
                results_sign_3_reg_1343_pp0_iter16_reg <= results_sign_3_reg_1343_pp0_iter15_reg;
                results_sign_3_reg_1343_pp0_iter9_reg <= results_sign_3_reg_1343;
                second_order_float_sin_cos_K1_load_reg_1398 <= second_order_float_sin_cos_K1_q0;
                second_order_float_sin_cos_K2_load_reg_1403 <= second_order_float_sin_cos_K2_q0;
                sin_basis_reg_1325 <= sin_basis_fu_568_p3;
                sin_basis_reg_1325_pp0_iter9_reg <= sin_basis_reg_1325;
                sub_ln506_reg_1314 <= sub_ln506_fu_551_p2;
                t1_reg_1393 <= second_order_float_sin_cos_K0_q0(29 downto 1);
                t1_reg_1393_pp0_iter12_reg <= t1_reg_1393;
                tmp_1_reg_1363 <= select_ln506_1_fu_801_p3(28 downto 22);
                tmp_3_reg_1438 <= grp_fu_292_p2(57 downto 42);
                tmp_4_reg_1443 <= grp_fu_292_p2(41 downto 29);
                tmp_7_reg_1284 <= Mx_bits_3_fu_432_p3(57 downto 29);
                tmp_reg_1308 <= Ex_1_fu_537_p2(7 downto 7);
                tmp_s_reg_1289 <= tmp_s_fu_447_p19;
                trunc_ln281_1_reg_1458 <= trunc_ln281_1_fu_1033_p1;
                trunc_ln281_reg_1453 <= trunc_ln281_fu_1017_p1;
                trunc_ln2_reg_1408 <= mul_ln29_fu_288_p2(44 downto 23);
                trunc_ln379_reg_1243 <= trunc_ln379_fu_359_p1;
                trunc_ln3_reg_1413 <= mul_ln30_fu_910_p2(29 downto 16);
                trunc_ln5_reg_1448 <= grp_fu_292_p2(56 downto 29);
                trunc_ln_reg_1269 <= grp_fu_296_p2(79 downto 77);
            end if;
        end if;
    end process;
    A_fu_844_p3 <= (sin_basis_reg_1325_pp0_iter9_reg & tmp_1_reg_1363);
    B_fu_808_p1 <= select_ln506_1_fu_801_p3(22 - 1 downto 0);
    Ex_1_fu_537_p2 <= std_logic_vector(unsigned(select_ln453_fu_492_p3) - unsigned(trunc_ln505_fu_533_p1));
    Ex_2_fu_818_p3 <= 
        ap_const_lv8_0 when (cos_basis_reg_1319(0) = '1') else 
        Ex_1_reg_1302;
    Ex_fu_487_p2 <= std_logic_vector(unsigned(din_exp_reg_1219_pp0_iter7_reg) + unsigned(ap_const_lv8_83));
    Mx_1_fu_812_p3 <= 
        ap_const_lv29_1FFFFFFF when (cos_basis_reg_1319(0) = '1') else 
        Mx_reg_1296;
    Mx_bits_1_fu_427_p2 <= std_logic_vector(unsigned(ap_const_lv58_0) - unsigned(Mx_bits_reg_1263));
    Mx_bits_3_fu_432_p3 <= 
        Mx_bits_1_fu_427_p2 when (trunc_ln491_fu_423_p1(0) = '1') else 
        Mx_bits_reg_1263;
    Mx_zeros_fu_506_p1 <= (tmp_7_reg_1284 & ap_const_lv1_1);
    X_fu_380_p3 <= (ap_const_lv1_1 & din_sig_reg_1226_pp0_iter1_reg);
    add_ln300_fu_1081_p2 <= std_logic_vector(signed(sext_ln252_fu_1053_p1) + signed(ap_const_lv9_7F));
    add_ln32_1_fu_941_p2 <= std_logic_vector(unsigned(add_ln32_fu_932_p2) + unsigned(sext_ln32_2_fu_938_p1));
    add_ln32_fu_932_p2 <= std_logic_vector(signed(sext_ln32_fu_926_p1) + signed(sext_ln32_1_fu_929_p1));
    add_ln376_fu_330_p2 <= std_logic_vector(unsigned(din_exp_fu_312_p3) + unsigned(ap_const_lv8_C2));
    addr_fu_336_p3 <= 
        ap_const_lv8_3F when (closepath_fu_324_p2(0) = '1') else 
        add_ln376_fu_330_p2;
    and_ln271_fu_737_p2 <= (icmp_ln271_fu_732_p2 and icmp_ln271_1_reg_1258_pp0_iter7_reg);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= t_2_fu_1192_p4;
    c_1_fu_1025_p1 <= (tmp_4_reg_1443 & ap_const_lv19_40000);
    c_fu_1009_p1 <= (tmp_3_reg_1438 & ap_const_lv16_8000);
    closepath_fu_324_p2 <= "1" when (unsigned(din_exp_fu_312_p3) < unsigned(ap_const_lv8_7E)) else "0";
    cos_basis_fu_562_p3 <= 
        xor_ln242_fu_557_p2 when (do_cos_read_reg_1205_pp0_iter7_reg(0) = '1') else 
        tmp_s_reg_1289;
    data_fu_300_p1 <= t_in_int_reg;
    din_exp_fu_312_p3 <= data_fu_300_p1(30 downto 23);
    din_sig_fu_320_p1 <= data_fu_300_p1(23 - 1 downto 0);
    empty_59_fu_1129_p3 <= 
        tmp_6_fu_1110_p4 when (icmp_ln292_reg_1470(0) = '1') else 
        tmp_9_fu_1120_p4;
    empty_fu_1106_p1 <= newexp_fu_1087_p2(8 - 1 downto 0);
    grp_fu_292_p1 <= grp_fu_292_p10(29 - 1 downto 0);
    grp_fu_292_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_1_reg_1353_pp0_iter13_reg),58));
    grp_fu_296_p1 <= grp_fu_296_p10(24 - 1 downto 0);
    grp_fu_296_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(X_fu_380_p3),80));
    icmp_ln271_1_fu_392_p2 <= "1" when (din_sig_reg_1226_pp0_iter1_reg = ap_const_lv23_0) else "0";
    icmp_ln271_fu_732_p2 <= "1" when (din_exp_reg_1219_pp0_iter7_reg = ap_const_lv8_0) else "0";
    icmp_ln282_fu_752_p2 <= "1" when (din_exp_reg_1219_pp0_iter7_reg = ap_const_lv8_FF) else "0";
    icmp_ln292_fu_1042_p2 <= "1" when (trunc_ln281_fu_1017_p1 = ap_const_lv5_10) else "0";
    icmp_ln306_fu_1048_p2 <= "1" when (result_reg_1433 = ap_const_lv29_0) else "0";
    in_shift_1_fu_1037_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln5_reg_1448),to_integer(unsigned('0' & zext_ln281_fu_1021_p1(28-1 downto 0)))));
    in_shift_2_fu_1066_p2 <= std_logic_vector(shift_left(unsigned(in_shift_1_reg_1464),to_integer(unsigned('0' & zext_ln281_1_fu_1056_p1(28-1 downto 0)))));
    index_fu_574_p3 <= (din_sign_reg_1213_pp0_iter7_reg & k_reg_1274);
    k_fu_417_p3 <= 
        ap_const_lv3_0 when (closepath_reg_1232_pp0_iter6_reg(0) = '1') else 
        trunc_ln_reg_1269;
    lshr_ln506_fu_789_p2 <= std_logic_vector(shift_right(unsigned(zext_ln506_fu_786_p1),to_integer(unsigned('0' & zext_ln506_1_fu_782_p1(31-1 downto 0)))));
    lshr_ln_fu_344_p4 <= addr_fu_336_p3(7 downto 4);
    mul_ln23_fu_860_p0 <= zext_ln23_fu_857_p1(15 - 1 downto 0);
    mul_ln23_fu_860_p1 <= zext_ln23_fu_857_p1(15 - 1 downto 0);
    mul_ln29_fu_288_p1 <= mul_ln29_fu_288_p10(22 - 1 downto 0);
    mul_ln29_fu_288_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_reg_1348_pp0_iter11_reg),45));
    mul_ln30_fu_910_p0 <= mul_ln30_fu_910_p00(15 - 1 downto 0);
    mul_ln30_fu_910_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_squared_reg_1388),30));
    newexp_fu_1087_p2 <= std_logic_vector(unsigned(add_ln300_fu_1081_p2) - unsigned(zext_ln286_fu_1077_p1));
    or_ln282_fu_1150_p2 <= (or_ln306_fu_1101_p2 or icmp_ln282_reg_1336_pp0_iter16_reg);
    or_ln306_fu_1101_p2 <= (tmp_2_fu_1093_p3 or icmp_ln306_reg_1476);
    ref_4oPi_table_100_address0 <= zext_ln378_fu_354_p1(4 - 1 downto 0);

    ref_4oPi_table_100_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            ref_4oPi_table_100_ce0_local <= ap_const_logic_1;
        else 
            ref_4oPi_table_100_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    results_exp_1_fu_1178_p3 <= 
        select_ln259_fu_1136_p3 when (and_ln271_reg_1330_pp0_iter16_reg(0) = '1') else 
        results_exp_fu_1155_p3;
    results_exp_fu_1155_p3 <= 
        select_ln282_fu_1143_p3 when (or_ln282_fu_1150_p2(0) = '1') else 
        empty_fu_1106_p1;
    results_sig_1_fu_1185_p3 <= 
        ap_const_lv23_0 when (and_ln271_reg_1330_pp0_iter16_reg(0) = '1') else 
        results_sig_fu_1170_p3;
    results_sig_fu_1170_p3 <= 
        select_ln282_2_fu_1163_p3 when (or_ln282_fu_1150_p2(0) = '1') else 
        empty_59_fu_1129_p3;
    results_sign_2_fu_747_p2 <= (xor_ln278_fu_742_p2 and din_sign_reg_1213_pp0_iter7_reg);
    results_sign_3_fu_769_p3 <= 
        results_sign_2_fu_747_p2 when (and_ln271_fu_737_p2(0) = '1') else 
        results_sign_4_fu_763_p2;
    results_sign_4_fu_763_p2 <= (xor_ln282_fu_757_p2 and results_sign_fu_724_p3);
    results_sign_fu_724_p3 <= 
        tmp_8_fu_580_p35 when (cos_basis_fu_562_p3(0) = '1') else 
        tmp_5_fu_652_p35;
    second_order_float_sin_cos_K0_address0 <= zext_ln28_fu_850_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K0_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            second_order_float_sin_cos_K0_ce0_local <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_sin_cos_K1_address0 <= zext_ln28_fu_850_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K1_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            second_order_float_sin_cos_K1_ce0_local <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_sin_cos_K2_address0 <= zext_ln28_fu_850_p1(8 - 1 downto 0);

    second_order_float_sin_cos_K2_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            second_order_float_sin_cos_K2_ce0_local <= ap_const_logic_1;
        else 
            second_order_float_sin_cos_K2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln259_fu_1136_p3 <= 
        ap_const_lv8_7F when (do_cos_read_reg_1205_pp0_iter16_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln282_2_fu_1163_p3 <= 
        ap_const_lv23_7FFFFF when (icmp_ln282_reg_1336_pp0_iter16_reg(0) = '1') else 
        ap_const_lv23_0;
    select_ln282_fu_1143_p3 <= 
        ap_const_lv8_FF when (icmp_ln282_reg_1336_pp0_iter16_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln453_fu_492_p3 <= 
        Ex_fu_487_p2 when (closepath_reg_1232_pp0_iter7_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln506_1_fu_801_p3 <= 
        lshr_ln506_fu_789_p2 when (tmp_reg_1308(0) = '1') else 
        shl_ln506_fu_795_p2;
    select_ln506_fu_777_p3 <= 
        sub_ln506_reg_1314 when (tmp_reg_1308(0) = '1') else 
        Ex_1_reg_1302;
        sext_ln252_fu_1053_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ex_2_reg_1358_pp0_iter16_reg),9));

        sext_ln32_1_fu_929_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_reg_1408),30));

        sext_ln32_2_fu_938_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln3_reg_1413),30));

        sext_ln32_fu_926_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t1_reg_1393_pp0_iter12_reg),30));

    shift_1_fu_1059_p3 <= (ap_const_lv1_1 & trunc_ln281_1_reg_1458);
    shift_2_fu_1071_p3 <= 
        shift_1_fu_1059_p3 when (icmp_ln292_reg_1470(0) = '1') else 
        trunc_ln281_reg_1453;
    shl_ln379_fu_366_p2 <= std_logic_vector(shift_left(unsigned(ref_4oPi_table_100_q0),to_integer(unsigned('0' & zext_ln379_fu_363_p1(31-1 downto 0)))));
    shl_ln504_fu_518_p2 <= std_logic_vector(shift_left(unsigned(Mx_bits_3_reg_1279),to_integer(unsigned('0' & zext_ln504_fu_514_p1(31-1 downto 0)))));
    shl_ln506_fu_795_p2 <= std_logic_vector(shift_left(unsigned(zext_ln506_fu_786_p1),to_integer(unsigned('0' & zext_ln506_1_fu_782_p1(31-1 downto 0)))));
    sin_basis_fu_568_p3 <= 
        tmp_s_reg_1289 when (do_cos_read_reg_1205_pp0_iter7_reg(0) = '1') else 
        xor_ln242_fu_557_p2;
    sub_ln506_fu_551_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(Ex_1_fu_537_p2));
    t_2_fu_1192_p4 <= ((results_sign_3_reg_1343_pp0_iter16_reg & results_exp_1_fu_1178_p3) & results_sig_1_fu_1185_p3);
    tmp_2_fu_1093_p3 <= newexp_fu_1087_p2(8 downto 8);
    tmp_5_fu_652_p33 <= "X";
    tmp_6_fu_1110_p4 <= in_shift_2_fu_1066_p2(27 downto 5);
    tmp_8_fu_580_p33 <= "X";
    tmp_9_fu_1120_p4 <= in_shift_1_reg_1464(27 downto 5);
    tmp_s_fu_447_p17 <= "X";
    trunc_ln281_1_fu_1033_p1 <= c_1_fu_1025_p3(4 - 1 downto 0);
    trunc_ln281_fu_1017_p1 <= c_fu_1009_p3(5 - 1 downto 0);
    trunc_ln379_fu_359_p1 <= addr_fu_336_p3(4 - 1 downto 0);
    trunc_ln491_fu_423_p1 <= k_fu_417_p3(1 - 1 downto 0);
    trunc_ln505_fu_533_p1 <= Mx_zeros_fu_506_p3(8 - 1 downto 0);
    xor_ln242_fu_557_p2 <= (tmp_s_reg_1289 xor ap_const_lv1_1);
    xor_ln278_fu_742_p2 <= (do_cos_read_reg_1205_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln282_fu_757_p2 <= (icmp_ln282_fu_752_p2 xor ap_const_lv1_1);
    zext_ln23_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_trunc_reg_1368_pp0_iter10_reg),30));
    zext_ln281_1_fu_1056_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln281_1_reg_1458),28));
    zext_ln281_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln281_fu_1017_p1),28));
    zext_ln286_fu_1077_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shift_2_fu_1071_p3),9));
    zext_ln28_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_fu_844_p3),64));
    zext_ln378_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_344_p4),64));
    zext_ln379_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln379_reg_1243),100));
    zext_ln504_fu_514_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_zeros_fu_506_p3),58));
    zext_ln506_1_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln506_fu_777_p3),32));
    zext_ln506_fu_786_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_reg_1296),32));
end behav;
