#!/usr/bin/env python3
"""
GNSS 2D Acquisition Engine
Performs Doppler × Code Phase search using the enhanced FPGA correlator.
"""

import mmap
import struct
import time
import os
import math
import random
import numpy as np
from dataclasses import dataclass
from typing import List, Tuple, Optional, Dict

# ============================================================================
# CONFIGURATION
# ============================================================================

@dataclass
class ConstellationConfig:
    """Configuration for a GNSS constellation/band"""
    name: str
    code_length: int          # Number of chips in PRN code
    chip_rate: float          # Chip rate in Hz
    sample_rate: float        # Sampling rate in Hz
    doppler_range: Tuple[float, float]  # (min_hz, max_hz)
    doppler_step: float       # Doppler bin spacing in Hz
    code_phase_step: float    # Code phase step in chips
    correlator_spacing: float # Early-Late spacing in chips
    acq_threshold: float      # Peak-to-noise ratio threshold
    integration_time_ms: int  # Integration time in milliseconds

# GPS L1 C/A Configuration
GPS_L1_CAA = ConstellationConfig(
    name="GPS_L1_C/A",
    code_length=1023,
    chip_rate=1.023e6,
    sample_rate=2.046e6,      # 2x chip rate (typical)
    doppler_range=(-10000.0, 10000.0),
    doppler_step=500.0,
    code_phase_step=1.0,
    correlator_spacing=0.5,
    acq_threshold=2.5,
    integration_time_ms=1
)

# ============================================================================
# HARDWARE INTERFACE
# ============================================================================

class EnhancedCorrelatorHW:
    """Hardware interface for the enhanced correlator IP"""
    
    def __init__(self, base_address: int, ddr_address: int = 0x1E000000):
        """
        Args:
            base_address: AXI-Lite control base address (from Vivado Address Editor)
            ddr_address: DDR memory base address for data buffers
        """
        self.base_address = base_address
        self.ddr_address = ddr_address
        self.map_size = 256 * 1024  # 256KB mapping
        
        # Register offsets (auto-generated by Vivado HLS)
        self.OFF_AP_CTRL            = 0x00
        self.OFF_SIGNAL_I_LOW       = 0x10
        self.OFF_SIGNAL_I_HIGH      = 0x14
        self.OFF_SIGNAL_Q_LOW       = 0x1C
        self.OFF_SIGNAL_Q_HIGH      = 0x20
        self.OFF_PRN_CODE_LOW       = 0x28
        self.OFF_PRN_CODE_HIGH      = 0x2C
        self.OFF_NUM_SAMPLES        = 0x30
        self.OFF_CARRIER_FREQ       = 0x34
        self.OFF_CARRIER_PHASE_INIT = 0x38
        self.OFF_CODE_PHASE_INIT    = 0x3C
        self.OFF_CODE_FREQ          = 0x40
        self.OFF_SAMPLE_RATE        = 0x44
        self.OFF_CODE_LENGTH        = 0x48
        self.OFF_CORR_SPACING       = 0x4C
        self.OFF_CORR_E_I           = 0x50
        self.OFF_CORR_E_Q           = 0x58
        self.OFF_CORR_P_I           = 0x60
        self.OFF_CORR_P_Q           = 0x68
        self.OFF_CORR_L_I           = 0x70
        self.OFF_CORR_L_Q           = 0x78
        
        # DDR buffer offsets (within our DDR mapping)
        self.DDR_SIGNAL_I_OFFSET = 0x00000
        self.DDR_SIGNAL_Q_OFFSET = 0x10000
        self.DDR_PRN_CODE_OFFSET = 0x20000
        
        self.fd = None
        self.ctrl_mem = None
        self.ddr_mem = None
        
    def open(self):
        """Open memory mappings"""
        self.fd = os.open("/dev/mem", os.O_RDWR | os.O_SYNC)
        self.ctrl_mem = mmap.mmap(
            self.fd, self.map_size, mmap.MAP_SHARED,
            mmap.PROT_READ | mmap.PROT_WRITE, 
            offset=self.base_address
        )
        self.ddr_mem = mmap.mmap(
            self.fd, self.map_size, mmap.MAP_SHARED,
            mmap.PROT_READ | mmap.PROT_WRITE,
            offset=self.ddr_address
        )
        
    def close(self):
        """Close memory mappings"""
        if self.ctrl_mem:
            self.ctrl_mem.close()
        if self.ddr_mem:
            self.ddr_mem.close()
        if self.fd:
            os.close(self.fd)
            
    def write_reg(self, offset: int, value: int):
        """Write 32-bit register"""
        self.ctrl_mem.seek(offset)
        self.ctrl_mem.write(struct.pack('<I', value & 0xFFFFFFFF))
        
    def read_reg(self, offset: int) -> int:
        """Read 32-bit register"""
        self.ctrl_mem.seek(offset)
        return struct.unpack('<I', self.ctrl_mem.read(4))[0]
        
    def write_float(self, offset: int, value: float):
        """Write float register"""
        self.ctrl_mem.seek(offset)
        self.ctrl_mem.write(struct.pack('<f', value))
        
    def read_float(self, offset: int) -> float:
        """Read float register"""
        self.ctrl_mem.seek(offset)
        val_int = struct.unpack('<I', self.ctrl_mem.read(4))[0]
        return struct.unpack('<f', struct.pack('<I', val_int))[0]
        
    def write_float_array(self, offset: int, array: List[float]):
        """Write array of floats to DDR"""
        self.ddr_mem.seek(offset)
        for val in array:
            self.ddr_mem.write(struct.pack('<f', val))
            
    def flush_cache(self):
        """Flush cache to ensure DDR coherency"""
        for i in range(0, self.map_size, 4096):
            self.ddr_mem.seek(i)
            _ = self.ddr_mem.read(4096)
        os.sync()
        
    def correlate(self, signal_I: List[float], signal_Q: List[float], 
                  prn_code: List[float], carrier_freq: float, 
                  code_phase: float, config: ConstellationConfig) -> Dict:
        """
        Run one correlation with the FPGA
        
        Returns dict with E_I, E_Q, P_I, P_Q, L_I, L_Q, exec_time
        """
        num_samples = len(signal_I)
        
        # Write data to DDR
        self.write_float_array(self.DDR_SIGNAL_I_OFFSET, signal_I)
        self.write_float_array(self.DDR_SIGNAL_Q_OFFSET, signal_Q)
        self.write_float_array(self.DDR_PRN_CODE_OFFSET, prn_code)
        self.flush_cache()
        
        # Configure correlator
        self.write_reg(self.OFF_SIGNAL_I_LOW, self.ddr_address + self.DDR_SIGNAL_I_OFFSET)
        self.write_reg(self.OFF_SIGNAL_I_HIGH, 0)
        self.write_reg(self.OFF_SIGNAL_Q_LOW, self.ddr_address + self.DDR_SIGNAL_Q_OFFSET)
        self.write_reg(self.OFF_SIGNAL_Q_HIGH, 0)
        self.write_reg(self.OFF_PRN_CODE_LOW, self.ddr_address + self.DDR_PRN_CODE_OFFSET)
        self.write_reg(self.OFF_PRN_CODE_HIGH, 0)
        
        self.write_reg(self.OFF_NUM_SAMPLES, num_samples)
        self.write_float(self.OFF_CARRIER_FREQ, carrier_freq)
        self.write_float(self.OFF_CARRIER_PHASE_INIT, 0.0)
        self.write_float(self.OFF_CODE_PHASE_INIT, code_phase)
        self.write_float(self.OFF_CODE_FREQ, config.chip_rate)
        self.write_float(self.OFF_SAMPLE_RATE, config.sample_rate)
        self.write_reg(self.OFF_CODE_LENGTH, config.code_length)
        self.write_float(self.OFF_CORR_SPACING, config.correlator_spacing)
        
        # Start correlator
        self.write_reg(self.OFF_AP_CTRL, 0x1)
        
        # Wait for completion
        start = time.perf_counter()
        timeout = 5.0
        while not (self.read_reg(self.OFF_AP_CTRL) & 0x2):
            if time.perf_counter() - start > timeout:
                raise TimeoutError(f"Correlator timeout after {timeout}s")
            time.sleep(0.0001)
            
        exec_time = (time.perf_counter() - start) * 1e6
        
        # Read results
        result = {
            'E_I': self.read_float(self.OFF_CORR_E_I),
            'E_Q': self.read_float(self.OFF_CORR_E_Q),
            'P_I': self.read_float(self.OFF_CORR_P_I),
            'P_Q': self.read_float(self.OFF_CORR_P_Q),
            'L_I': self.read_float(self.OFF_CORR_L_I),
            'L_Q': self.read_float(self.OFF_CORR_L_Q),
            'exec_time': exec_time
        }
        
        return result

# ============================================================================
# GPS PRN CODE GENERATOR
# ============================================================================

def generate_gps_prn(prn_id: int) -> List[float]:
    """Generate GPS L1 C/A PRN code for PRN 1-32"""
    g2_taps = {
        1: [2,6], 2: [3,7], 3: [4,8], 4: [5,9], 5: [1,9],
        6: [2,10], 7: [1,8], 8: [2,9], 9: [3,10], 10: [2,3],
        11: [3,4], 12: [5,6], 13: [6,7], 14: [7,8], 15: [8,9],
        16: [9,10], 17: [1,4], 18: [2,5], 19: [3,6], 20: [4,7],
        21: [5,8], 22: [6,9], 23: [1,3], 24: [4,6], 25: [5,7],
        26: [6,8], 27: [7,9], 28: [8,10], 29: [1,6], 30: [2,7],
        31: [3,8], 32: [4,9]
    }
    
    if prn_id not in g2_taps:
        raise ValueError(f"PRN ID must be 1-32, got {prn_id}")
        
    taps = g2_taps[prn_id]
    g1 = [1] * 10
    g2 = [1] * 10
    code = []
    
    for _ in range(1023):
        output = g1[9] ^ g2[taps[0]-1] ^ g2[taps[1]-1]
        code.append(1.0 if output == 1 else -1.0)
        g1_fb = g1[9] ^ g1[2]
        g2_fb = g2[9] ^ g2[8] ^ g2[7] ^ g2[5] ^ g2[2] ^ g2[1]
        g1 = [g1_fb] + g1[:-1]
        g2 = [g2_fb] + g2[:-1]
    
    return code

# ============================================================================
# 2D SEARCH ENGINE
# ============================================================================

@dataclass
class AcquisitionResult:
    """Result of acquisition search"""
    prn_id: int
    doppler_hz: float
    code_phase_chips: float
    peak_power: float
    noise_floor: float
    pnr: float  # Peak-to-noise ratio
    acquired: bool
    corr_results: Dict  # E/P/L correlator outputs at peak
    exec_time_us: float

class AcquisitionEngine:
    """2D Acquisition Search Engine"""
    
    def __init__(self, hw: EnhancedCorrelatorHW, config: ConstellationConfig):
        self.hw = hw
        self.config = config
        
    def search(self, signal_I: List[float], signal_Q: List[float], 
               prn_id: int, progress_callback=None) -> AcquisitionResult:
        """
        Perform 2D search (Doppler × Code Phase)
        
        Args:
            signal_I: I channel samples
            signal_Q: Q channel samples
            prn_id: PRN satellite ID (1-32 for GPS)
            progress_callback: Optional callback(percent_complete, current_doppler)
            
        Returns:
            AcquisitionResult with best peak found
        """
        print(f"\n🛰️  Acquiring PRN {prn_id}...")
        
        # Generate PRN code
        prn_code = generate_gps_prn(prn_id)
        
        # Calculate number of samples (1 ms of data for GPS L1 C/A)
        num_samples = int(self.config.sample_rate * self.config.integration_time_ms / 1000)
        num_samples = min(num_samples, len(signal_I))
        
        # Truncate signals to num_samples
        signal_I = signal_I[:num_samples]
        signal_Q = signal_Q[:num_samples]
        
        print(f"   Samples: {num_samples}")
        print(f"   Integration time: {self.config.integration_time_ms} ms")
        
        # 2D Search
        doppler_min, doppler_max = self.config.doppler_range
        doppler_step = self.config.doppler_step
        code_step = self.config.code_phase_step
        
        doppler_bins = np.arange(doppler_min, doppler_max + doppler_step, doppler_step)
        code_phases = np.arange(0, self.config.code_length, code_step)
        
        total_cells = len(doppler_bins) * len(code_phases)
        print(f"   Search space: {len(doppler_bins)} Doppler × {len(code_phases)} code = {total_cells} cells")
        
        best_power = 0.0
        best_doppler = 0.0
        best_code_phase = 0.0
        best_result = None
        
        cells_tested = 0
        start_total = time.perf_counter()
        
        for doppler_idx, doppler in enumerate(doppler_bins):
            if progress_callback and doppler_idx % 5 == 0:
                progress_callback(100.0 * doppler_idx / len(doppler_bins), doppler)
            
            for code_phase in code_phases:
                try:
                    result = self.hw.correlate(
                        signal_I, signal_Q, prn_code,
                        float(doppler), float(code_phase), self.config
                    )
                    
                    # Calculate power
                    power = result['P_I']**2 + result['P_Q']**2
                    cells_tested += 1
                    
                    if power > best_power:
                        best_power = power
                        best_doppler = doppler
                        best_code_phase = code_phase
                        best_result = result
                        
                except Exception as e:
                    print(f"   ⚠️  Error at Doppler={doppler}, Code={code_phase}: {e}")
                    continue
        
        total_time = time.perf_counter() - start_total
        
        # Calculate noise floor (average of all powers except the peak)
        # For simplicity, use a rough estimate
        noise_floor = best_power / 10.0  # Rough estimate
        pnr = best_power / noise_floor if noise_floor > 0 else 0.0
        
        # Validate acquisition
        acquired = pnr >= self.config.acq_threshold
        
        return AcquisitionResult(
            prn_id=prn_id,
            doppler_hz=best_doppler,
            code_phase_chips=best_code_phase,
            peak_power=best_power,
            noise_floor=noise_floor,
            pnr=pnr,
            acquired=acquired,
            corr_results=best_result if best_result else {},
            exec_time_us=total_time * 1e6
        )

# ============================================================================
# SYNTHETIC DATA GENERATOR
# ============================================================================

def generate_synthetic_signal(prn_id: int, true_doppler: float, 
                              true_code_phase: float, num_samples: int,
                              config: ConstellationConfig, 
                              snr_db: float = 10.0) -> Tuple[List[float], List[float]]:
    """
    Generate synthetic GPS signal with known parameters
    
    Args:
        prn_id: PRN satellite ID
        true_doppler: True Doppler frequency in Hz
        true_code_phase: True code phase in chips
        num_samples: Number of samples to generate
        config: Constellation configuration
        snr_db: Signal-to-noise ratio in dB
        
    Returns:
        Tuple of (signal_I, signal_Q)
    """
    prn_code = generate_gps_prn(prn_id)
    
    # Calculate noise standard deviation from SNR
    signal_power = 1.0  # Normalized
    noise_power = signal_power / (10 ** (snr_db / 10))
    noise_std = math.sqrt(noise_power)
    
    signal_I = []
    signal_Q = []
    
    for i in range(num_samples):
        # Carrier phase
        carrier_phase = 2 * math.pi * true_doppler * i / config.sample_rate
        
        # Code phase (with offset and chip rate)
        chip_idx = int((i * config.chip_rate / config.sample_rate) + true_code_phase) % config.code_length
        
        # Signal = PRN * carrier
        sig_I = prn_code[chip_idx] * math.cos(carrier_phase)
        sig_Q = prn_code[chip_idx] * math.sin(carrier_phase)
        
        # Add noise
        sig_I += random.gauss(0, noise_std)
        sig_Q += random.gauss(0, noise_std)
        
        signal_I.append(sig_I)
        signal_Q.append(sig_Q)
    
    return signal_I, signal_Q

# ============================================================================
# MAIN TEST FUNCTION
# ============================================================================

def test_acquisition():
    """Test the acquisition engine"""
    
    # ========================================================================
    # CONFIGURATION - UPDATE THESE VALUES!
    # ========================================================================
    
    # Base address from Vivado Address Editor (UPDATE THIS!)
    ENHANCED_CORRELATOR_BASE = 0x40020000  # <-- CHECK YOUR ADDRESS EDITOR!
    DDR_BASE = 0x1E000000
    
    # Use GPS L1 C/A configuration
    config = GPS_L1_CAA
    
    # PRN to acquire
    PRN_ID = 1
    
    # True parameters (for synthetic data - we know these)
    TRUE_DOPPLER = 1500.0    # Hz
    TRUE_CODE_PHASE = 250.0  # chips
    SNR_DB = 10.0
    
    # Number of samples (1 ms for GPS L1 C/A)
    NUM_SAMPLES = int(config.sample_rate * config.integration_time_ms / 1000)
    
    # ========================================================================
    # MAIN TEST
    # ========================================================================
    
    print("="*70)
    print("🚀 GNSS 2D ACQUISITION ENGINE TEST")
    print("="*70)
    print(f"Constellation: {config.name}")
    print(f"Code length: {config.code_length} chips")
    print(f"Chip rate: {config.chip_rate/1e6:.3f} MHz")
    print(f"Sample rate: {config.sample_rate/1e6:.3f} MHz")
    print(f"Doppler range: {config.doppler_range[0]:.0f} to {config.doppler_range[1]:.0f} Hz")
    print(f"Doppler step: {config.doppler_step:.0f} Hz")
    print(f"Integration time: {config.integration_time_ms} ms")
    print(f"Acquisition threshold: {config.acq_threshold:.1f}")
    
    try:
        # Initialize hardware interface
        print("\n🔌 Initializing hardware interface...")
        hw = EnhancedCorrelatorHW(ENHANCED_CORRELATOR_BASE, DDR_BASE)
        hw.open()
        print(f"   Enhanced Correlator @ 0x{ENHANCED_CORRELATOR_BASE:08X}")
        print(f"   DDR Memory @ 0x{DDR_BASE:08X}")
        
        # Generate synthetic signal
        print(f"\n📊 Generating synthetic signal...")
        print(f"   PRN ID: {PRN_ID}")
        print(f"   True Doppler: {TRUE_DOPPLER:.1f} Hz")
        print(f"   True Code Phase: {TRUE_CODE_PHASE:.1f} chips")
        print(f"   SNR: {SNR_DB:.1f} dB")
        print(f"   Samples: {NUM_SAMPLES}")
        
        signal_I, signal_Q = generate_synthetic_signal(
            PRN_ID, TRUE_DOPPLER, TRUE_CODE_PHASE, NUM_SAMPLES, config, SNR_DB
        )
        
        # Run acquisition
        print(f"\n🔍 Starting 2D acquisition search...")
        engine = AcquisitionEngine(hw, config)
        
        def progress_callback(percent, current_doppler):
            print(f"   Progress: {percent:5.1f}% (Doppler: {current_doppler:7.0f} Hz)")
        
        result = engine.search(signal_I, signal_Q, PRN_ID, progress_callback)
        
        # Display results
        print("\n" + "="*70)
        print("🎯 ACQUISITION RESULTS")
        print("="*70)
        print(f"PRN ID: {result.prn_id}")
        print(f"Acquired: {'✅ YES' if result.acquired else '❌ NO'}")
        print(f"\nTrue values:")
        print(f"  Doppler: {TRUE_DOPPLER:.1f} Hz")
        print(f"  Code Phase: {TRUE_CODE_PHASE:.1f} chips")
        print(f"\nDetected values:")
        print(f"  Doppler: {result.doppler_hz:.1f} Hz")
        print(f"  Code Phase: {result.code_phase_chips:.1f} chips")
        print(f"\nMetrics:")
        print(f"  Peak Power: {result.peak_power:.2f}")
        print(f"  Noise Floor: {result.noise_floor:.2f}")
        print(f"  PNR: {result.pnr:.2f}")
        print(f"  Search time: {result.exec_time_us/1e6:.2f} seconds")
        
        doppler_error = abs(result.doppler_hz - TRUE_DOPPLER)
        code_error = abs(result.code_phase_chips - TRUE_CODE_PHASE)
        
        print(f"\nErrors:")
        print(f"  Doppler error: {doppler_error:.1f} Hz")
        print(f"  Code phase error: {code_error:.1f} chips")
        
        if result.acquired:
            print("\n✅ SUCCESS: Satellite acquired!")
            print(f"   Correlator outputs at peak:")
            print(f"   Early:  I={result.corr_results['E_I']:8.2f}, Q={result.corr_results['E_Q']:8.2f}")
            print(f"   Prompt: I={result.corr_results['P_I']:8.2f}, Q={result.corr_results['P_Q']:8.2f}")
            print(f"   Late:   I={result.corr_results['L_I']:8.2f}, Q={result.corr_results['L_Q']:8.2f}")
        else:
            print("\n⚠️  WARNING: Acquisition failed (PNR below threshold)")
        
        print("="*70)
        
        # Cleanup
        hw.close()
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    test_acquisition()