[GNSS-SDR]
GNSS=GPS
GNSS-SDR.internal_fs_sps=2600000

######### SIGNAL_SOURCE CONFIG ############
SignalSource.implementation=File_Signal_Source
SignalSource.filename=/home/johan2/Documents/fpga/zynq-pynq-gnss-receiver/gps-sdr-sim/gpssim_float.bin
SignalSource.item_type=gr_complex
SignalSource.sampling_frequency=2600000

######### SIGNAL_CONDITIONER CONFIG ############
SignalConditioner.implementation=Signal_Conditioner
DataTypeAdapter.implementation=Pass_Through
InputFilter.implementation=Pass_Through
InputFilter.item_type=gr_complex
Resampler.implementation=Pass_Through

######### CHANNELS CONFIG ############
Channels_1C.count=4
Channels.in_acquisition=1

######### ACQUISITION CONFIG ############
Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition
Acquisition_1C.item_type=gr_complex
Acquisition_1C.dump=false
Acquisition_1C.pfa=0.01
Acquisition_1C.doppler_max=10000
Acquisition_1C.doppler_step=500

######### TRACKING CONFIG ############
Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking
Tracking_1C.item_type=gr_complex
Tracking_1C.dump=false

######### TELEMETRY DECODER CONFIG ############
TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder
TelemetryDecoder_1C.dump=false

######### OBSERVABLES CONFIG ############
Observables.implementation=Hybrid_Observables
Observables.dump=false

######### PVT CONFIG ############
PVT.implementation=RTKLIB_PVT
PVT.positioning_mode=Single