// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gnss_correlator_gnss_correlator,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=3931,HLS_SYN_LUT=5651,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module gnss_correlator (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt,
        s_axi_control_r_AWVALID,
        s_axi_control_r_AWREADY,
        s_axi_control_r_AWADDR,
        s_axi_control_r_WVALID,
        s_axi_control_r_WREADY,
        s_axi_control_r_WDATA,
        s_axi_control_r_WSTRB,
        s_axi_control_r_ARVALID,
        s_axi_control_r_ARREADY,
        s_axi_control_r_ARADDR,
        s_axi_control_r_RVALID,
        s_axi_control_r_RREADY,
        s_axi_control_r_RDATA,
        s_axi_control_r_RRESP,
        s_axi_control_r_BVALID,
        s_axi_control_r_BREADY,
        s_axi_control_r_BRESP
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_ADDR_WIDTH = 6;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;
input   s_axi_control_r_AWVALID;
output   s_axi_control_r_AWREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_AWADDR;
input   s_axi_control_r_WVALID;
output   s_axi_control_r_WREADY;
input  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_WDATA;
input  [C_S_AXI_CONTROL_R_WSTRB_WIDTH - 1:0] s_axi_control_r_WSTRB;
input   s_axi_control_r_ARVALID;
output   s_axi_control_r_ARREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_ARADDR;
output   s_axi_control_r_RVALID;
input   s_axi_control_r_RREADY;
output  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_RDATA;
output  [1:0] s_axi_control_r_RRESP;
output   s_axi_control_r_BVALID;
input   s_axi_control_r_BREADY;
output  [1:0] s_axi_control_r_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] signal_I;
wire   [63:0] signal_Q;
wire   [63:0] code_I;
wire   [63:0] code_Q;
reg    corr_I_ap_vld;
reg    corr_Q_ap_vld;
wire   [31:0] num_samples;
reg   [31:0] num_samples_read_reg_502;
reg   [61:0] trunc_ln_reg_519;
reg   [61:0] trunc_ln30_1_reg_524;
reg   [61:0] trunc_ln30_2_reg_529;
reg   [61:0] trunc_ln30_3_reg_534;
wire   [0:0] icmp_ln45_fu_236_p2;
reg   [0:0] icmp_ln45_reg_539;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_fu_242_p3;
reg   [0:0] tmp_reg_544;
wire   [17:0] select_ln45_fu_256_p3;
reg   [17:0] select_ln45_reg_549;
wire   [4:0] trunc_ln45_fu_272_p1;
reg   [4:0] trunc_ln45_reg_554;
wire   [4:0] add_ln45_fu_276_p2;
reg   [4:0] add_ln45_reg_559;
wire   [0:0] icmp_ln46_fu_282_p2;
reg   [0:0] icmp_ln46_reg_564;
wire   [0:0] tmp_8_fu_288_p3;
reg   [0:0] tmp_8_reg_569;
wire   [17:0] select_ln46_fu_302_p3;
reg   [17:0] select_ln46_reg_574;
wire   [4:0] trunc_ln46_fu_318_p1;
reg   [4:0] trunc_ln46_reg_579;
wire   [4:0] add_ln46_fu_322_p2;
reg   [4:0] add_ln46_reg_584;
wire   [31:0] retval_0_i_i69_fu_408_p3;
reg   [31:0] retval_0_i_i69_reg_589;
wire    ap_CS_fsm_state4;
wire   [31:0] retval_0_i_i_fu_495_p3;
reg   [31:0] retval_0_i_i_reg_594;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_idle;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_ready;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWID;
wire   [31:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWUSER;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WVALID;
wire   [31:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WDATA;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WSTRB;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WID;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WUSER;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARID;
wire   [31:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARUSER;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_RREADY;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_BREADY;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWID;
wire   [31:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWUSER;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WVALID;
wire   [31:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WDATA;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WSTRB;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WID;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WUSER;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARID;
wire   [31:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARUSER;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_RREADY;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_BREADY;
wire   [17:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out_ap_vld;
wire   [17:0] grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out;
wire    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out_ap_vld;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [31:0] gmem0_0_RDATA;
wire   [8:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
reg    gmem1_0_ARVALID;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
reg    gmem1_0_RREADY;
wire   [31:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
reg    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state5;
wire   [17:0] sub_ln45_fu_250_p2;
wire   [17:0] tmp_5_fu_264_p1;
wire   [17:0] tmp_5_fu_264_p3;
wire   [17:0] sub_ln46_fu_296_p2;
wire   [17:0] tmp_s_fu_310_p1;
wire   [17:0] tmp_s_fu_310_p3;
wire   [42:0] zext_ln45_fu_328_p1;
wire   [42:0] zext_ln45_1_fu_331_p1;
wire   [42:0] shl_ln45_fu_334_p2;
wire   [41:0] lshr_ln_fu_340_p4;
wire   [0:0] tmp_6_fu_354_p3;
wire   [4:0] sub_ln45_1_fu_370_p2;
wire  signed [7:0] sext_ln45_fu_375_p1;
wire   [7:0] select_ln45_1_fu_362_p3;
wire   [7:0] add_ln45_1_fu_379_p2;
wire   [63:0] zext_ln45_2_fu_350_p1;
wire   [8:0] tmp_7_fu_385_p3;
wire   [63:0] pi_assign_fu_392_p5;
wire   [31:0] LD_fu_404_p1;
wire   [42:0] zext_ln46_fu_415_p1;
wire   [42:0] zext_ln46_1_fu_418_p1;
wire   [42:0] shl_ln46_fu_421_p2;
wire   [41:0] lshr_ln1_fu_427_p4;
wire   [0:0] tmp_9_fu_441_p3;
wire   [4:0] sub_ln46_1_fu_457_p2;
wire  signed [7:0] sext_ln46_fu_462_p1;
wire   [7:0] select_ln46_1_fu_449_p3;
wire   [7:0] add_ln46_1_fu_466_p2;
wire   [63:0] zext_ln46_2_fu_437_p1;
wire   [8:0] tmp_10_fu_472_p3;
wire   [63:0] pi_assign_1_fu_479_p5;
wire   [31:0] LD_4_fu_491_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire   [17:0] tmp_5_fu_264_p0;
wire   [0:0] tmp_5_fu_264_p2;
wire   [17:0] tmp_s_fu_310_p0;
wire   [0:0] tmp_s_fu_310_p2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg = 1'b0;
end

gnss_correlator_gnss_correlator_Pipeline_VITIS_LOOP_30_1 grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start),
    .ap_done(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done),
    .ap_idle(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_idle),
    .ap_ready(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .m_axi_gmem1_0_AWVALID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .num_samples(num_samples_read_reg_502),
    .sext_ln30(trunc_ln_reg_519),
    .sext_ln30_1(trunc_ln30_1_reg_524),
    .sext_ln30_2(trunc_ln30_2_reg_529),
    .sext_ln30_3(trunc_ln30_3_reg_534),
    .acc_Q_out(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out),
    .acc_Q_out_ap_vld(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out_ap_vld),
    .acc_I_out(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out),
    .acc_I_out_ap_vld(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out_ap_vld)
);

gnss_correlator_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .corr_I(retval_0_i_i69_reg_589),
    .corr_I_ap_vld(corr_I_ap_vld),
    .corr_Q(retval_0_i_i_reg_594),
    .corr_Q_ap_vld(corr_Q_ap_vld),
    .num_samples(num_samples),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

gnss_correlator_control_r_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_R_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_R_DATA_WIDTH ))
control_r_s_axi_U(
    .AWVALID(s_axi_control_r_AWVALID),
    .AWREADY(s_axi_control_r_AWREADY),
    .AWADDR(s_axi_control_r_AWADDR),
    .WVALID(s_axi_control_r_WVALID),
    .WREADY(s_axi_control_r_WREADY),
    .WDATA(s_axi_control_r_WDATA),
    .WSTRB(s_axi_control_r_WSTRB),
    .ARVALID(s_axi_control_r_ARVALID),
    .ARREADY(s_axi_control_r_ARREADY),
    .ARADDR(s_axi_control_r_ARADDR),
    .RVALID(s_axi_control_r_RVALID),
    .RREADY(s_axi_control_r_RREADY),
    .RDATA(s_axi_control_r_RDATA),
    .RRESP(s_axi_control_r_RRESP),
    .BVALID(s_axi_control_r_BVALID),
    .BREADY(s_axi_control_r_BREADY),
    .BRESP(s_axi_control_r_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .signal_I(signal_I),
    .signal_Q(signal_Q),
    .code_I(code_I),
    .code_Q(code_Q)
);

gnss_correlator_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARADDR),
    .I_CH0_ARLEN(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

gnss_correlator_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem1_0_ARVALID),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARADDR),
    .I_CH0_ARLEN(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLEN),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(gmem1_0_RREADY),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

gnss_correlator_ctlz_18_18_1_1 #(
    .din_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
ctlz_18_18_1_1_U25(
    .din(tmp_5_fu_264_p1),
    .dout(tmp_5_fu_264_p3)
);

gnss_correlator_ctlz_18_18_1_1 #(
    .din_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
ctlz_18_18_1_1_U26(
    .din(tmp_s_fu_310_p1),
    .dout(tmp_s_fu_310_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_ready == 1'b1)) begin
            grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln45_reg_559 <= add_ln45_fu_276_p2;
        add_ln46_reg_584 <= add_ln46_fu_322_p2;
        icmp_ln45_reg_539 <= icmp_ln45_fu_236_p2;
        icmp_ln46_reg_564 <= icmp_ln46_fu_282_p2;
        select_ln45_reg_549 <= select_ln45_fu_256_p3;
        select_ln46_reg_574 <= select_ln46_fu_302_p3;
        tmp_8_reg_569 <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out[32'd17];
        tmp_reg_544 <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out[32'd17];
        trunc_ln45_reg_554 <= trunc_ln45_fu_272_p1;
        trunc_ln46_reg_579 <= trunc_ln46_fu_318_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        num_samples_read_reg_502 <= num_samples;
        trunc_ln30_1_reg_524 <= {{signal_Q[63:2]}};
        trunc_ln30_2_reg_529 <= {{code_I[63:2]}};
        trunc_ln30_3_reg_534 <= {{code_Q[63:2]}};
        trunc_ln_reg_519 <= {{signal_I[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        retval_0_i_i69_reg_589 <= retval_0_i_i69_fu_408_p3;
        retval_0_i_i_reg_594 <= retval_0_i_i_fu_495_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        corr_I_ap_vld = 1'b1;
    end else begin
        corr_I_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        corr_Q_ap_vld = 1'b1;
    end else begin
        corr_Q_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem0_0_ARVALID = grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARVALID;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem0_0_RREADY = grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_RREADY;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem1_0_ARVALID = grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARVALID;
    end else begin
        gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem1_0_RREADY = grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_RREADY;
    end else begin
        gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_4_fu_491_p1 = pi_assign_1_fu_479_p5[31:0];

assign LD_fu_404_p1 = pi_assign_fu_392_p5[31:0];

assign add_ln45_1_fu_379_p2 = ($signed(sext_ln45_fu_375_p1) + $signed(select_ln45_1_fu_362_p3));

assign add_ln45_fu_276_p2 = (trunc_ln45_fu_272_p1 + 5'd7);

assign add_ln46_1_fu_466_p2 = ($signed(sext_ln46_fu_462_p1) + $signed(select_ln46_1_fu_449_p3));

assign add_ln46_fu_322_p2 = (trunc_ln46_fu_318_p1 + 5'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start = grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg;

assign icmp_ln45_fu_236_p2 = ((grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_282_p2 = ((grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out == 18'd0) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_427_p4 = {{shl_ln46_fu_421_p2[42:1]}};

assign lshr_ln_fu_340_p4 = {{shl_ln45_fu_334_p2[42:1]}};

assign pi_assign_1_fu_479_p5 = {{zext_ln46_2_fu_437_p1[63:32]}, {tmp_10_fu_472_p3}, {zext_ln46_2_fu_437_p1[22:0]}};

assign pi_assign_fu_392_p5 = {{zext_ln45_2_fu_350_p1[63:32]}, {tmp_7_fu_385_p3}, {zext_ln45_2_fu_350_p1[22:0]}};

assign retval_0_i_i69_fu_408_p3 = ((icmp_ln45_reg_539[0:0] == 1'b1) ? 32'd0 : LD_fu_404_p1);

assign retval_0_i_i_fu_495_p3 = ((icmp_ln46_reg_564[0:0] == 1'b1) ? 32'd0 : LD_4_fu_491_p1);

assign select_ln45_1_fu_362_p3 = ((tmp_6_fu_354_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln45_fu_256_p3 = ((tmp_fu_242_p3[0:0] == 1'b1) ? sub_ln45_fu_250_p2 : grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out);

assign select_ln46_1_fu_449_p3 = ((tmp_9_fu_441_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln46_fu_302_p3 = ((tmp_8_fu_288_p3[0:0] == 1'b1) ? sub_ln46_fu_296_p2 : grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out);

assign sext_ln45_fu_375_p1 = $signed(sub_ln45_1_fu_370_p2);

assign sext_ln46_fu_462_p1 = $signed(sub_ln46_1_fu_457_p2);

assign shl_ln45_fu_334_p2 = zext_ln45_fu_328_p1 << zext_ln45_1_fu_331_p1;

assign shl_ln46_fu_421_p2 = zext_ln46_fu_415_p1 << zext_ln46_1_fu_418_p1;

assign sub_ln45_1_fu_370_p2 = (5'd2 - trunc_ln45_reg_554);

assign sub_ln45_fu_250_p2 = (18'd0 - grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out);

assign sub_ln46_1_fu_457_p2 = (5'd2 - trunc_ln46_reg_579);

assign sub_ln46_fu_296_p2 = (18'd0 - grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out);

assign tmp_10_fu_472_p3 = {{tmp_8_reg_569}, {add_ln46_1_fu_466_p2}};

assign tmp_5_fu_264_p1 = ((tmp_fu_242_p3[0:0] == 1'b1) ? sub_ln45_fu_250_p2 : grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out);

assign tmp_6_fu_354_p3 = shl_ln45_fu_334_p2[32'd25];

assign tmp_7_fu_385_p3 = {{tmp_reg_544}, {add_ln45_1_fu_379_p2}};

assign tmp_8_fu_288_p3 = grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out[32'd17];

assign tmp_9_fu_441_p3 = shl_ln46_fu_421_p2[32'd25];

assign tmp_fu_242_p3 = grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out[32'd17];

assign tmp_s_fu_310_p1 = ((tmp_8_fu_288_p3[0:0] == 1'b1) ? sub_ln46_fu_296_p2 : grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out);

assign trunc_ln45_fu_272_p1 = tmp_5_fu_264_p3[4:0];

assign trunc_ln46_fu_318_p1 = tmp_s_fu_310_p3[4:0];

assign zext_ln45_1_fu_331_p1 = add_ln45_reg_559;

assign zext_ln45_2_fu_350_p1 = lshr_ln_fu_340_p4;

assign zext_ln45_fu_328_p1 = select_ln45_reg_549;

assign zext_ln46_1_fu_418_p1 = add_ln46_reg_584;

assign zext_ln46_2_fu_437_p1 = lshr_ln1_fu_427_p4;

assign zext_ln46_fu_415_p1 = select_ln46_reg_574;

endmodule //gnss_correlator
