-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gnss_correlator is
generic (
    C_M_AXI_GMEM0_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM0_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM0_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM1_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM1_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_S_AXI_CONTROL_R_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_R_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM0_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM0_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM0_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM1_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM1_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM1_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ADDR_WIDTH-1 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH-1 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_WUSER_WIDTH-1 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ADDR_WIDTH-1 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH-1 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_RUSER_WIDTH-1 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_BUSER_WIDTH-1 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ADDR_WIDTH-1 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH-1 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_WUSER_WIDTH-1 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ADDR_WIDTH-1 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH-1 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_RUSER_WIDTH-1 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC;
    s_axi_control_r_AWVALID : IN STD_LOGIC;
    s_axi_control_r_AWREADY : OUT STD_LOGIC;
    s_axi_control_r_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_ADDR_WIDTH-1 downto 0);
    s_axi_control_r_WVALID : IN STD_LOGIC;
    s_axi_control_r_WREADY : OUT STD_LOGIC;
    s_axi_control_r_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_DATA_WIDTH-1 downto 0);
    s_axi_control_r_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_DATA_WIDTH/8-1 downto 0);
    s_axi_control_r_ARVALID : IN STD_LOGIC;
    s_axi_control_r_ARREADY : OUT STD_LOGIC;
    s_axi_control_r_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_ADDR_WIDTH-1 downto 0);
    s_axi_control_r_RVALID : OUT STD_LOGIC;
    s_axi_control_r_RREADY : IN STD_LOGIC;
    s_axi_control_r_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_R_DATA_WIDTH-1 downto 0);
    s_axi_control_r_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_r_BVALID : OUT STD_LOGIC;
    s_axi_control_r_BREADY : IN STD_LOGIC;
    s_axi_control_r_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of gnss_correlator is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "gnss_correlator_gnss_correlator,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=3931,HLS_SYN_LUT=5651,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal signal_I : STD_LOGIC_VECTOR (63 downto 0);
    signal signal_Q : STD_LOGIC_VECTOR (63 downto 0);
    signal code_I : STD_LOGIC_VECTOR (63 downto 0);
    signal code_Q : STD_LOGIC_VECTOR (63 downto 0);
    signal corr_I_ap_vld : STD_LOGIC;
    signal corr_Q_ap_vld : STD_LOGIC;
    signal num_samples : STD_LOGIC_VECTOR (31 downto 0);
    signal num_samples_read_reg_502 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln_reg_519 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln30_1_reg_524 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln30_2_reg_529 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln30_3_reg_534 : STD_LOGIC_VECTOR (61 downto 0);
    signal icmp_ln45_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_539 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_fu_242_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_544 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln45_fu_256_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln45_reg_549 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln45_fu_272_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln45_reg_554 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln45_fu_276_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln45_reg_559 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln46_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_564 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_288_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_fu_302_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln46_reg_574 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln46_fu_318_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln46_reg_579 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln46_fu_322_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln46_reg_584 : STD_LOGIC_VECTOR (4 downto 0);
    signal retval_0_i_i69_fu_408_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_0_i_i69_reg_589 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal retval_0_i_i_fu_495_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_0_i_i_reg_594 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_idle : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_ready : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWVALID : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WVALID : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WLAST : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARVALID : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_RREADY : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_BREADY : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out_ap_vld : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out_ap_vld : STD_LOGIC;
    signal gmem0_0_AWREADY : STD_LOGIC;
    signal gmem0_0_WREADY : STD_LOGIC;
    signal gmem0_0_ARVALID : STD_LOGIC;
    signal gmem0_0_ARREADY : STD_LOGIC;
    signal gmem0_0_RVALID : STD_LOGIC;
    signal gmem0_0_RREADY : STD_LOGIC;
    signal gmem0_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem0_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem0_0_BVALID : STD_LOGIC;
    signal gmem1_0_AWREADY : STD_LOGIC;
    signal gmem1_0_WREADY : STD_LOGIC;
    signal gmem1_0_ARVALID : STD_LOGIC;
    signal gmem1_0_ARREADY : STD_LOGIC;
    signal gmem1_0_RVALID : STD_LOGIC;
    signal gmem1_0_RREADY : STD_LOGIC;
    signal gmem1_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem1_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem1_0_BVALID : STD_LOGIC;
    signal grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sub_ln45_fu_250_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_5_fu_264_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_5_fu_264_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln46_fu_296_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_fu_310_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_fu_310_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln45_fu_328_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln45_1_fu_331_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal shl_ln45_fu_334_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal lshr_ln_fu_340_p4 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_6_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln45_1_fu_370_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln45_fu_375_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln45_1_fu_362_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln45_1_fu_379_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_2_fu_350_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_7_fu_385_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_fu_392_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_fu_404_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln46_fu_415_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln46_1_fu_418_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal shl_ln46_fu_421_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal lshr_ln1_fu_427_p4 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_9_fu_441_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln46_1_fu_457_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln46_fu_462_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_1_fu_449_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln46_1_fu_466_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln46_2_fu_437_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_10_fu_472_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_1_fu_479_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_4_fu_491_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal tmp_5_fu_264_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_5_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_310_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component gnss_correlator_gnss_correlator_Pipeline_VITIS_LOOP_30_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_WREADY : IN STD_LOGIC;
        m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RVALID : IN STD_LOGIC;
        m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_RLAST : IN STD_LOGIC;
        m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BVALID : IN STD_LOGIC;
        m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        num_samples : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln30 : IN STD_LOGIC_VECTOR (61 downto 0);
        sext_ln30_1 : IN STD_LOGIC_VECTOR (61 downto 0);
        sext_ln30_2 : IN STD_LOGIC_VECTOR (61 downto 0);
        sext_ln30_3 : IN STD_LOGIC_VECTOR (61 downto 0);
        acc_Q_out : OUT STD_LOGIC_VECTOR (17 downto 0);
        acc_Q_out_ap_vld : OUT STD_LOGIC;
        acc_I_out : OUT STD_LOGIC_VECTOR (17 downto 0);
        acc_I_out_ap_vld : OUT STD_LOGIC );
    end component;


    component gnss_correlator_ctlz_18_18_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component gnss_correlator_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        corr_I : IN STD_LOGIC_VECTOR (31 downto 0);
        corr_I_ap_vld : IN STD_LOGIC;
        corr_Q : IN STD_LOGIC_VECTOR (31 downto 0);
        corr_Q_ap_vld : IN STD_LOGIC;
        num_samples : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component gnss_correlator_control_r_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        signal_I : OUT STD_LOGIC_VECTOR (63 downto 0);
        signal_Q : OUT STD_LOGIC_VECTOR (63 downto 0);
        code_I : OUT STD_LOGIC_VECTOR (63 downto 0);
        code_Q : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component gnss_correlator_gmem0_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component gnss_correlator_gmem1_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170 : component gnss_correlator_gnss_correlator_Pipeline_VITIS_LOOP_30_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start,
        ap_done => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done,
        ap_idle => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_idle,
        ap_ready => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_ready,
        m_axi_gmem0_0_AWVALID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_0_AWADDR => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => ap_const_logic_0,
        m_axi_gmem0_0_WDATA => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST => ap_const_logic_0,
        m_axi_gmem0_0_RID => ap_const_lv1_0,
        m_axi_gmem0_0_RFIFONUM => gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER => ap_const_lv1_0,
        m_axi_gmem0_0_RRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BVALID => ap_const_logic_0,
        m_axi_gmem0_0_BREADY => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BID => ap_const_lv1_0,
        m_axi_gmem0_0_BUSER => ap_const_lv1_0,
        m_axi_gmem1_0_AWVALID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY => ap_const_logic_0,
        m_axi_gmem1_0_AWADDR => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY => ap_const_logic_0,
        m_axi_gmem1_0_WDATA => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY => gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID => gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA => gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST => ap_const_logic_0,
        m_axi_gmem1_0_RID => ap_const_lv1_0,
        m_axi_gmem1_0_RFIFONUM => gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER => ap_const_lv1_0,
        m_axi_gmem1_0_RRESP => ap_const_lv2_0,
        m_axi_gmem1_0_BVALID => ap_const_logic_0,
        m_axi_gmem1_0_BREADY => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP => ap_const_lv2_0,
        m_axi_gmem1_0_BID => ap_const_lv1_0,
        m_axi_gmem1_0_BUSER => ap_const_lv1_0,
        num_samples => num_samples_read_reg_502,
        sext_ln30 => trunc_ln_reg_519,
        sext_ln30_1 => trunc_ln30_1_reg_524,
        sext_ln30_2 => trunc_ln30_2_reg_529,
        sext_ln30_3 => trunc_ln30_3_reg_534,
        acc_Q_out => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out,
        acc_Q_out_ap_vld => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out_ap_vld,
        acc_I_out => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out,
        acc_I_out_ap_vld => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out_ap_vld);

    control_s_axi_U : component gnss_correlator_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        corr_I => retval_0_i_i69_reg_589,
        corr_I_ap_vld => corr_I_ap_vld,
        corr_Q => retval_0_i_i_reg_594,
        corr_Q_ap_vld => corr_Q_ap_vld,
        num_samples => num_samples,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    control_r_s_axi_U : component gnss_correlator_control_r_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_R_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_R_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_r_AWVALID,
        AWREADY => s_axi_control_r_AWREADY,
        AWADDR => s_axi_control_r_AWADDR,
        WVALID => s_axi_control_r_WVALID,
        WREADY => s_axi_control_r_WREADY,
        WDATA => s_axi_control_r_WDATA,
        WSTRB => s_axi_control_r_WSTRB,
        ARVALID => s_axi_control_r_ARVALID,
        ARREADY => s_axi_control_r_ARREADY,
        ARADDR => s_axi_control_r_ARADDR,
        RVALID => s_axi_control_r_RVALID,
        RREADY => s_axi_control_r_RREADY,
        RDATA => s_axi_control_r_RDATA,
        RRESP => s_axi_control_r_RRESP,
        BVALID => s_axi_control_r_BVALID,
        BREADY => s_axi_control_r_BREADY,
        BRESP => s_axi_control_r_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        signal_I => signal_I,
        signal_Q => signal_Q,
        code_I => code_I,
        code_Q => code_Q);

    gmem0_m_axi_U : component gnss_correlator_gmem0_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM0_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM0_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM0_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM0_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM0_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM0_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM0_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM0_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM0_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM0_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM0_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem0_AWVALID,
        AWREADY => m_axi_gmem0_AWREADY,
        AWADDR => m_axi_gmem0_AWADDR,
        AWID => m_axi_gmem0_AWID,
        AWLEN => m_axi_gmem0_AWLEN,
        AWSIZE => m_axi_gmem0_AWSIZE,
        AWBURST => m_axi_gmem0_AWBURST,
        AWLOCK => m_axi_gmem0_AWLOCK,
        AWCACHE => m_axi_gmem0_AWCACHE,
        AWPROT => m_axi_gmem0_AWPROT,
        AWQOS => m_axi_gmem0_AWQOS,
        AWREGION => m_axi_gmem0_AWREGION,
        AWUSER => m_axi_gmem0_AWUSER,
        WVALID => m_axi_gmem0_WVALID,
        WREADY => m_axi_gmem0_WREADY,
        WDATA => m_axi_gmem0_WDATA,
        WSTRB => m_axi_gmem0_WSTRB,
        WLAST => m_axi_gmem0_WLAST,
        WID => m_axi_gmem0_WID,
        WUSER => m_axi_gmem0_WUSER,
        ARVALID => m_axi_gmem0_ARVALID,
        ARREADY => m_axi_gmem0_ARREADY,
        ARADDR => m_axi_gmem0_ARADDR,
        ARID => m_axi_gmem0_ARID,
        ARLEN => m_axi_gmem0_ARLEN,
        ARSIZE => m_axi_gmem0_ARSIZE,
        ARBURST => m_axi_gmem0_ARBURST,
        ARLOCK => m_axi_gmem0_ARLOCK,
        ARCACHE => m_axi_gmem0_ARCACHE,
        ARPROT => m_axi_gmem0_ARPROT,
        ARQOS => m_axi_gmem0_ARQOS,
        ARREGION => m_axi_gmem0_ARREGION,
        ARUSER => m_axi_gmem0_ARUSER,
        RVALID => m_axi_gmem0_RVALID,
        RREADY => m_axi_gmem0_RREADY,
        RDATA => m_axi_gmem0_RDATA,
        RLAST => m_axi_gmem0_RLAST,
        RID => m_axi_gmem0_RID,
        RUSER => m_axi_gmem0_RUSER,
        RRESP => m_axi_gmem0_RRESP,
        BVALID => m_axi_gmem0_BVALID,
        BREADY => m_axi_gmem0_BREADY,
        BRESP => m_axi_gmem0_BRESP,
        BID => m_axi_gmem0_BID,
        BUSER => m_axi_gmem0_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem0_0_ARVALID,
        I_CH0_ARREADY => gmem0_0_ARREADY,
        I_CH0_ARADDR => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARADDR,
        I_CH0_ARLEN => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARLEN,
        I_CH0_RVALID => gmem0_0_RVALID,
        I_CH0_RREADY => gmem0_0_RREADY,
        I_CH0_RDATA => gmem0_0_RDATA,
        I_CH0_RFIFONUM => gmem0_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem0_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem0_0_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => gmem0_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    gmem1_m_axi_U : component gnss_correlator_gmem1_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM1_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM1_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM1_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM1_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM1_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM1_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM1_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM1_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM1_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM1_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM1_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem1_AWVALID,
        AWREADY => m_axi_gmem1_AWREADY,
        AWADDR => m_axi_gmem1_AWADDR,
        AWID => m_axi_gmem1_AWID,
        AWLEN => m_axi_gmem1_AWLEN,
        AWSIZE => m_axi_gmem1_AWSIZE,
        AWBURST => m_axi_gmem1_AWBURST,
        AWLOCK => m_axi_gmem1_AWLOCK,
        AWCACHE => m_axi_gmem1_AWCACHE,
        AWPROT => m_axi_gmem1_AWPROT,
        AWQOS => m_axi_gmem1_AWQOS,
        AWREGION => m_axi_gmem1_AWREGION,
        AWUSER => m_axi_gmem1_AWUSER,
        WVALID => m_axi_gmem1_WVALID,
        WREADY => m_axi_gmem1_WREADY,
        WDATA => m_axi_gmem1_WDATA,
        WSTRB => m_axi_gmem1_WSTRB,
        WLAST => m_axi_gmem1_WLAST,
        WID => m_axi_gmem1_WID,
        WUSER => m_axi_gmem1_WUSER,
        ARVALID => m_axi_gmem1_ARVALID,
        ARREADY => m_axi_gmem1_ARREADY,
        ARADDR => m_axi_gmem1_ARADDR,
        ARID => m_axi_gmem1_ARID,
        ARLEN => m_axi_gmem1_ARLEN,
        ARSIZE => m_axi_gmem1_ARSIZE,
        ARBURST => m_axi_gmem1_ARBURST,
        ARLOCK => m_axi_gmem1_ARLOCK,
        ARCACHE => m_axi_gmem1_ARCACHE,
        ARPROT => m_axi_gmem1_ARPROT,
        ARQOS => m_axi_gmem1_ARQOS,
        ARREGION => m_axi_gmem1_ARREGION,
        ARUSER => m_axi_gmem1_ARUSER,
        RVALID => m_axi_gmem1_RVALID,
        RREADY => m_axi_gmem1_RREADY,
        RDATA => m_axi_gmem1_RDATA,
        RLAST => m_axi_gmem1_RLAST,
        RID => m_axi_gmem1_RID,
        RUSER => m_axi_gmem1_RUSER,
        RRESP => m_axi_gmem1_RRESP,
        BVALID => m_axi_gmem1_BVALID,
        BREADY => m_axi_gmem1_BREADY,
        BRESP => m_axi_gmem1_BRESP,
        BID => m_axi_gmem1_BID,
        BUSER => m_axi_gmem1_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem1_0_ARVALID,
        I_CH0_ARREADY => gmem1_0_ARREADY,
        I_CH0_ARADDR => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARADDR,
        I_CH0_ARLEN => grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARLEN,
        I_CH0_RVALID => gmem1_0_RVALID,
        I_CH0_RREADY => gmem1_0_RREADY,
        I_CH0_RDATA => gmem1_0_RDATA,
        I_CH0_RFIFONUM => gmem1_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem1_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem1_0_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => gmem1_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    ctlz_18_18_1_1_U25 : component gnss_correlator_ctlz_18_18_1_1
    generic map (
        din_WIDTH => 18,
        dout_WIDTH => 18)
    port map (
        din => tmp_5_fu_264_p1,
        dout => tmp_5_fu_264_p3);

    ctlz_18_18_1_1_U26 : component gnss_correlator_ctlz_18_18_1_1
    generic map (
        din_WIDTH => 18,
        dout_WIDTH => 18)
    port map (
        din => tmp_s_fu_310_p1,
        dout => tmp_s_fu_310_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_ready = ap_const_logic_1)) then 
                    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln45_reg_559 <= add_ln45_fu_276_p2;
                add_ln46_reg_584 <= add_ln46_fu_322_p2;
                icmp_ln45_reg_539 <= icmp_ln45_fu_236_p2;
                icmp_ln46_reg_564 <= icmp_ln46_fu_282_p2;
                select_ln45_reg_549 <= select_ln45_fu_256_p3;
                select_ln46_reg_574 <= select_ln46_fu_302_p3;
                tmp_8_reg_569 <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out(17 downto 17);
                tmp_reg_544 <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out(17 downto 17);
                trunc_ln45_reg_554 <= trunc_ln45_fu_272_p1;
                trunc_ln46_reg_579 <= trunc_ln46_fu_318_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                num_samples_read_reg_502 <= num_samples;
                trunc_ln30_1_reg_524 <= signal_Q(63 downto 2);
                trunc_ln30_2_reg_529 <= code_I(63 downto 2);
                trunc_ln30_3_reg_534 <= code_Q(63 downto 2);
                trunc_ln_reg_519 <= signal_I(63 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                retval_0_i_i69_reg_589 <= retval_0_i_i69_fu_408_p3;
                retval_0_i_i_reg_594 <= retval_0_i_i_fu_495_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    LD_4_fu_491_p1 <= pi_assign_1_fu_479_p5(32 - 1 downto 0);
    LD_fu_404_p1 <= pi_assign_fu_392_p5(32 - 1 downto 0);
    add_ln45_1_fu_379_p2 <= std_logic_vector(signed(sext_ln45_fu_375_p1) + signed(select_ln45_1_fu_362_p3));
    add_ln45_fu_276_p2 <= std_logic_vector(unsigned(trunc_ln45_fu_272_p1) + unsigned(ap_const_lv5_7));
    add_ln46_1_fu_466_p2 <= std_logic_vector(signed(sext_ln46_fu_462_p1) + signed(select_ln46_1_fu_449_p3));
    add_ln46_fu_322_p2 <= std_logic_vector(unsigned(trunc_ln46_fu_318_p1) + unsigned(ap_const_lv5_7));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done)
    begin
        if ((grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    corr_I_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            corr_I_ap_vld <= ap_const_logic_1;
        else 
            corr_I_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    corr_Q_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            corr_Q_ap_vld <= ap_const_logic_1;
        else 
            corr_Q_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_0_ARVALID_assign_proc : process(ap_CS_fsm_state1, grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARVALID, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem0_0_ARVALID <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_ARVALID;
        else 
            gmem0_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_0_RREADY_assign_proc : process(ap_CS_fsm_state1, grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_RREADY, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem0_0_RREADY <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem0_0_RREADY;
        else 
            gmem0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem1_0_ARVALID_assign_proc : process(ap_CS_fsm_state1, grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARVALID, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem1_0_ARVALID <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_ARVALID;
        else 
            gmem1_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem1_0_RREADY_assign_proc : process(ap_CS_fsm_state1, grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_RREADY, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem1_0_RREADY <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_m_axi_gmem1_0_RREADY;
        else 
            gmem1_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_ap_start_reg;
    icmp_ln45_fu_236_p2 <= "1" when (grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out = ap_const_lv18_0) else "0";
    icmp_ln46_fu_282_p2 <= "1" when (grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out = ap_const_lv18_0) else "0";
    lshr_ln1_fu_427_p4 <= shl_ln46_fu_421_p2(42 downto 1);
    lshr_ln_fu_340_p4 <= shl_ln45_fu_334_p2(42 downto 1);
    pi_assign_1_fu_479_p5 <= (zext_ln46_2_fu_437_p1(63 downto 32) & tmp_10_fu_472_p3 & zext_ln46_2_fu_437_p1(22 downto 0));
    pi_assign_fu_392_p5 <= (zext_ln45_2_fu_350_p1(63 downto 32) & tmp_7_fu_385_p3 & zext_ln45_2_fu_350_p1(22 downto 0));
    retval_0_i_i69_fu_408_p3 <= 
        ap_const_lv32_0 when (icmp_ln45_reg_539(0) = '1') else 
        LD_fu_404_p1;
    retval_0_i_i_fu_495_p3 <= 
        ap_const_lv32_0 when (icmp_ln46_reg_564(0) = '1') else 
        LD_4_fu_491_p1;
    select_ln45_1_fu_362_p3 <= 
        ap_const_lv8_7F when (tmp_6_fu_354_p3(0) = '1') else 
        ap_const_lv8_7E;
    select_ln45_fu_256_p3 <= 
        sub_ln45_fu_250_p2 when (tmp_fu_242_p3(0) = '1') else 
        grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out;
    select_ln46_1_fu_449_p3 <= 
        ap_const_lv8_7F when (tmp_9_fu_441_p3(0) = '1') else 
        ap_const_lv8_7E;
    select_ln46_fu_302_p3 <= 
        sub_ln46_fu_296_p2 when (tmp_8_fu_288_p3(0) = '1') else 
        grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out;
        sext_ln45_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln45_1_fu_370_p2),8));

        sext_ln46_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln46_1_fu_457_p2),8));

    shl_ln45_fu_334_p2 <= std_logic_vector(shift_left(unsigned(zext_ln45_fu_328_p1),to_integer(unsigned('0' & zext_ln45_1_fu_331_p1(31-1 downto 0)))));
    shl_ln46_fu_421_p2 <= std_logic_vector(shift_left(unsigned(zext_ln46_fu_415_p1),to_integer(unsigned('0' & zext_ln46_1_fu_418_p1(31-1 downto 0)))));
    sub_ln45_1_fu_370_p2 <= std_logic_vector(unsigned(ap_const_lv5_2) - unsigned(trunc_ln45_reg_554));
    sub_ln45_fu_250_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out));
    sub_ln46_1_fu_457_p2 <= std_logic_vector(unsigned(ap_const_lv5_2) - unsigned(trunc_ln46_reg_579));
    sub_ln46_fu_296_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out));
    tmp_10_fu_472_p3 <= (tmp_8_reg_569 & add_ln46_1_fu_466_p2);
    tmp_5_fu_264_p1 <= 
        sub_ln45_fu_250_p2 when (tmp_fu_242_p3(0) = '1') else 
        grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out;
    tmp_6_fu_354_p3 <= shl_ln45_fu_334_p2(25 downto 25);
    tmp_7_fu_385_p3 <= (tmp_reg_544 & add_ln45_1_fu_379_p2);
    tmp_8_fu_288_p3 <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out(17 downto 17);
    tmp_9_fu_441_p3 <= shl_ln46_fu_421_p2(25 downto 25);
    tmp_fu_242_p3 <= grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_I_out(17 downto 17);
    tmp_s_fu_310_p1 <= 
        sub_ln46_fu_296_p2 when (tmp_8_fu_288_p3(0) = '1') else 
        grp_gnss_correlator_Pipeline_VITIS_LOOP_30_1_fu_170_acc_Q_out;
    trunc_ln45_fu_272_p1 <= tmp_5_fu_264_p3(5 - 1 downto 0);
    trunc_ln46_fu_318_p1 <= tmp_s_fu_310_p3(5 - 1 downto 0);
    zext_ln45_1_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln45_reg_559),43));
    zext_ln45_2_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_340_p4),64));
    zext_ln45_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_reg_549),43));
    zext_ln46_1_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_reg_584),43));
    zext_ln46_2_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_427_p4),64));
    zext_ln46_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln46_reg_574),43));
end behav;
