// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gnss_correlator_gnss_correlator_Pipeline_VITIS_LOOP_30_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        num_samples,
        sext_ln30,
        sext_ln30_1,
        sext_ln30_2,
        sext_ln30_3,
        acc_Q_out,
        acc_Q_out_ap_vld,
        acc_I_out,
        acc_I_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [31:0] m_axi_gmem0_0_WDATA;
output  [3:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [31:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [8:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [31:0] m_axi_gmem1_0_WDATA;
output  [3:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [31:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [8:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [31:0] num_samples;
input  [61:0] sext_ln30;
input  [61:0] sext_ln30_1;
input  [61:0] sext_ln30_2;
input  [61:0] sext_ln30_3;
output  [17:0] acc_Q_out;
output   acc_Q_out_ap_vld;
output  [17:0] acc_I_out;
output   acc_I_out_ap_vld;

reg ap_idle;
reg m_axi_gmem0_0_ARVALID;
reg[63:0] m_axi_gmem0_0_ARADDR;
reg m_axi_gmem0_0_RREADY;
reg m_axi_gmem1_0_ARVALID;
reg[63:0] m_axi_gmem1_0_ARADDR;
reg m_axi_gmem1_0_RREADY;
reg acc_Q_out_ap_vld;
reg acc_I_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln30_reg_1344;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_state2_io_grp2;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone_grp5_done_reg;
reg    ap_block_pp0_stage1_subdone_grp5;
reg    ap_block_pp0_stage1_subdone_grp6_done_reg;
reg    ap_block_pp0_stage1_subdone_grp6;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_block_pp0_stage1_grp2;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage1_grp6;
wire    ap_block_pp0_stage0_grp4;
reg    ap_block_pp0_stage0_subdone_grp4_done_reg;
reg    ap_block_pp0_stage0_subdone_grp4;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0_grp8;
reg    ap_block_pp0_stage0_subdone_grp8_done_reg;
reg    ap_block_pp0_stage0_subdone_grp8;
reg    gmem0_blk_n_AR;
wire    ap_block_pp0_stage1_grp1;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage1_grp5;
wire    ap_block_pp0_stage0_grp3;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
wire    ap_block_pp0_stage0_grp7;
reg    ap_block_pp0_stage0_subdone_grp7_done_reg;
reg    ap_block_pp0_stage0_subdone_grp7;
reg   [31:0] reg_204;
reg    ap_block_pp0_stage1_11001_grp5;
reg    ap_block_pp0_stage0_11001_grp7;
reg   [31:0] reg_208;
reg    ap_block_pp0_stage1_11001_grp6;
reg    ap_block_pp0_stage0_11001_grp8;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] icmp_ln30_fu_250_p2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter1_reg;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter2_reg;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter3_reg;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter4_reg;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter5_reg;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter6_reg;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter7_reg;
reg   [0:0] icmp_ln30_reg_1344_pp0_iter8_reg;
reg   [63:0] gmem0_addr_reg_1348;
reg   [63:0] gmem0_addr_1_reg_1354;
reg   [63:0] gmem1_addr_reg_1360;
reg   [63:0] gmem1_addr_1_reg_1366;
wire   [31:0] bitcast_ln34_fu_335_p1;
wire   [31:0] bitcast_ln36_fu_340_p1;
wire   [62:0] trunc_ln34_fu_349_p1;
reg   [62:0] trunc_ln34_reg_1382;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg   [0:0] tmp_reg_1387;
reg   [10:0] tmp_1_reg_1393;
wire   [51:0] trunc_ln34_1_fu_369_p1;
reg   [51:0] trunc_ln34_1_reg_1398;
wire   [31:0] bitcast_ln35_fu_373_p1;
wire   [62:0] trunc_ln36_fu_382_p1;
reg   [62:0] trunc_ln36_reg_1408;
reg   [0:0] tmp_3_reg_1413;
reg   [10:0] tmp_s_reg_1419;
wire   [51:0] trunc_ln36_1_fu_402_p1;
reg   [51:0] trunc_ln36_1_reg_1424;
wire   [31:0] bitcast_ln37_fu_406_p1;
wire   [53:0] select_ln34_fu_431_p3;
reg   [53:0] select_ln34_reg_1434;
wire   [0:0] icmp_ln34_fu_438_p2;
reg   [0:0] icmp_ln34_reg_1439;
wire   [0:0] icmp_ln34_1_fu_453_p2;
reg   [0:0] icmp_ln34_1_reg_1446;
wire   [10:0] select_ln34_1_fu_471_p3;
reg   [10:0] select_ln34_1_reg_1451;
wire   [0:0] icmp_ln34_2_fu_479_p2;
reg   [0:0] icmp_ln34_2_reg_1459;
wire   [17:0] trunc_ln34_3_fu_485_p1;
reg   [17:0] trunc_ln34_3_reg_1465;
wire   [62:0] trunc_ln35_fu_493_p1;
reg   [62:0] trunc_ln35_reg_1471;
reg   [0:0] tmp_2_reg_1476;
reg   [10:0] tmp_9_reg_1482;
wire   [51:0] trunc_ln35_1_fu_513_p1;
reg   [51:0] trunc_ln35_1_reg_1487;
wire   [53:0] select_ln36_fu_537_p3;
reg   [53:0] select_ln36_reg_1492;
wire   [0:0] icmp_ln36_fu_544_p2;
reg   [0:0] icmp_ln36_reg_1497;
wire   [0:0] icmp_ln36_1_fu_559_p2;
reg   [0:0] icmp_ln36_1_reg_1504;
wire   [10:0] select_ln36_1_fu_577_p3;
reg   [10:0] select_ln36_1_reg_1509;
wire   [0:0] icmp_ln36_2_fu_585_p2;
reg   [0:0] icmp_ln36_2_reg_1517;
wire   [17:0] trunc_ln36_3_fu_591_p1;
reg   [17:0] trunc_ln36_3_reg_1523;
wire   [62:0] trunc_ln37_fu_599_p1;
reg   [62:0] trunc_ln37_reg_1529;
reg   [0:0] tmp_4_reg_1534;
reg   [10:0] tmp_5_reg_1540;
wire   [51:0] trunc_ln37_1_fu_619_p1;
reg   [51:0] trunc_ln37_1_reg_1545;
wire   [17:0] select_ln34_2_fu_647_p3;
reg   [17:0] select_ln34_2_reg_1550;
wire   [17:0] select_ln34_3_fu_668_p3;
reg   [17:0] select_ln34_3_reg_1555;
wire   [53:0] select_ln35_fu_696_p3;
reg   [53:0] select_ln35_reg_1560;
wire   [0:0] icmp_ln35_fu_703_p2;
reg   [0:0] icmp_ln35_reg_1565;
wire   [10:0] select_ln35_1_fu_736_p3;
reg   [10:0] select_ln35_1_reg_1571;
wire   [0:0] icmp_ln35_2_fu_744_p2;
reg   [0:0] icmp_ln35_2_reg_1579;
wire   [17:0] trunc_ln35_3_fu_750_p1;
reg   [17:0] trunc_ln35_3_reg_1584;
wire   [0:0] and_ln35_1_fu_766_p2;
reg   [0:0] and_ln35_1_reg_1590;
wire   [17:0] select_ln36_2_fu_796_p3;
reg   [17:0] select_ln36_2_reg_1595;
wire   [17:0] select_ln36_3_fu_817_p3;
reg   [17:0] select_ln36_3_reg_1600;
wire   [53:0] select_ln37_fu_845_p3;
reg   [53:0] select_ln37_reg_1605;
wire   [0:0] icmp_ln37_fu_852_p2;
reg   [0:0] icmp_ln37_reg_1610;
wire   [0:0] icmp_ln37_1_fu_867_p2;
reg   [0:0] icmp_ln37_1_reg_1617;
wire   [10:0] select_ln37_1_fu_885_p3;
reg   [10:0] select_ln37_1_reg_1622;
wire   [0:0] icmp_ln37_2_fu_893_p2;
reg   [0:0] icmp_ln37_2_reg_1630;
wire   [17:0] trunc_ln37_3_fu_899_p1;
reg   [17:0] trunc_ln37_3_reg_1636;
wire   [17:0] a_fu_937_p11;
reg  signed [17:0] a_reg_1642;
wire   [17:0] select_ln35_2_fu_982_p3;
reg   [17:0] select_ln35_2_reg_1647;
wire   [17:0] select_ln35_3_fu_1003_p3;
reg   [17:0] select_ln35_3_reg_1652;
wire   [17:0] c_fu_1045_p11;
reg  signed [17:0] c_reg_1657;
wire   [17:0] select_ln37_2_fu_1090_p3;
reg   [17:0] select_ln37_2_reg_1662;
wire   [17:0] select_ln37_3_fu_1111_p3;
reg   [17:0] select_ln37_3_reg_1667;
wire  signed [33:0] sext_ln40_fu_1213_p1;
reg  signed [33:0] sext_ln40_reg_1672;
wire  signed [33:0] sext_ln40_1_fu_1216_p1;
reg  signed [33:0] sext_ln40_1_reg_1677;
wire  signed [33:0] sext_ln40_2_fu_1219_p1;
reg  signed [33:0] sext_ln40_2_reg_1682;
wire  signed [33:0] sext_ln40_3_fu_1223_p1;
reg  signed [33:0] sext_ln40_3_reg_1688;
wire   [33:0] mul_ln40_fu_1227_p2;
reg  signed [33:0] mul_ln40_reg_1694;
wire   [33:0] mul_ln41_fu_1233_p2;
reg  signed [33:0] mul_ln41_reg_1699;
wire  signed [63:0] sext_ln34_fu_272_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln35_fu_288_p1;
wire  signed [63:0] sext_ln36_fu_304_p1;
wire  signed [63:0] sext_ln37_fu_320_p1;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_pp0_stage0_11001_grp3;
reg    ap_block_pp0_stage1_11001_grp2;
reg    ap_block_pp0_stage0_11001_grp4;
reg   [17:0] acc_I_fu_118;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_grp0;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage1_11001;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
wire    ap_block_pp0_stage1_grp0;
reg   [17:0] acc_Q_fu_122;
reg   [30:0] i_fu_126;
wire   [30:0] add_ln30_fu_256_p2;
reg   [30:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage1_01001_grp0;
reg   [31:0] grp_fu_198_p0;
reg   [31:0] grp_fu_201_p0;
wire   [31:0] zext_ln30_1_fu_246_p1;
wire   [62:0] zext_ln30_fu_262_p1;
wire  signed [62:0] sext_ln30_cast_fu_224_p1;
wire   [62:0] add_ln34_fu_266_p2;
wire  signed [62:0] sext_ln30_1_cast_fu_220_p1;
wire   [62:0] add_ln35_fu_282_p2;
wire  signed [62:0] sext_ln30_2_cast_fu_216_p1;
wire   [62:0] add_ln36_fu_298_p2;
wire  signed [62:0] sext_ln30_3_cast_fu_212_p1;
wire   [62:0] add_ln37_fu_314_p2;
wire   [63:0] grp_fu_198_p1;
wire   [63:0] bitcast_ln726_fu_345_p1;
wire   [63:0] grp_fu_201_p1;
wire   [63:0] bitcast_ln726_2_fu_378_p1;
wire   [52:0] zext_ln34_1_cast_fu_414_p3;
wire   [53:0] zext_ln34_1_fu_421_p1;
wire   [53:0] sub_ln34_fu_425_p2;
wire   [11:0] zext_ln34_fu_411_p1;
wire   [11:0] sub_ln34_1_fu_443_p2;
wire   [10:0] trunc_ln34_2_fu_449_p1;
wire   [10:0] add_ln34_1_fu_459_p2;
wire   [10:0] sub_ln34_2_fu_465_p2;
wire   [63:0] bitcast_ln726_1_fu_489_p1;
wire   [52:0] zext_ln36_1_cast_fu_520_p3;
wire   [53:0] zext_ln36_1_fu_527_p1;
wire   [53:0] sub_ln36_fu_531_p2;
wire   [11:0] zext_ln36_fu_517_p1;
wire   [11:0] sub_ln36_1_fu_549_p2;
wire   [10:0] trunc_ln36_2_fu_555_p1;
wire   [10:0] add_ln36_1_fu_565_p2;
wire   [10:0] sub_ln36_2_fu_571_p2;
wire   [63:0] bitcast_ln726_3_fu_595_p1;
wire   [53:0] zext_ln34_2_fu_635_p1;
wire   [53:0] ashr_ln34_fu_638_p2;
wire   [0:0] icmp_ln34_3_fu_623_p2;
wire   [17:0] trunc_ln34_4_fu_643_p1;
wire   [17:0] select_ln34_4_fu_628_p3;
wire   [17:0] select_ln34_1cast_fu_660_p1;
wire   [0:0] icmp_ln34_4_fu_655_p2;
wire   [17:0] shl_ln34_fu_663_p2;
wire   [52:0] zext_ln35_1_cast_fu_679_p3;
wire   [53:0] zext_ln35_1_fu_686_p1;
wire   [53:0] sub_ln35_fu_690_p2;
wire   [11:0] zext_ln35_fu_676_p1;
wire   [11:0] sub_ln35_1_fu_708_p2;
wire   [10:0] trunc_ln35_2_fu_714_p1;
wire   [0:0] icmp_ln35_1_fu_718_p2;
wire   [10:0] add_ln35_1_fu_724_p2;
wire   [10:0] sub_ln35_2_fu_730_p2;
wire   [0:0] or_ln35_fu_754_p2;
wire   [0:0] xor_ln35_1_fu_760_p2;
wire   [53:0] zext_ln36_2_fu_784_p1;
wire   [53:0] ashr_ln36_fu_787_p2;
wire   [0:0] icmp_ln36_3_fu_772_p2;
wire   [17:0] trunc_ln36_4_fu_792_p1;
wire   [17:0] select_ln36_4_fu_777_p3;
wire   [17:0] select_ln36_1cast_fu_809_p1;
wire   [0:0] icmp_ln36_4_fu_804_p2;
wire   [17:0] shl_ln36_fu_812_p2;
wire   [52:0] zext_ln37_1_cast_fu_828_p3;
wire   [53:0] zext_ln37_1_fu_835_p1;
wire   [53:0] sub_ln37_fu_839_p2;
wire   [11:0] zext_ln37_fu_825_p1;
wire   [11:0] sub_ln37_1_fu_857_p2;
wire   [10:0] trunc_ln37_2_fu_863_p1;
wire   [10:0] add_ln37_1_fu_873_p2;
wire   [10:0] sub_ln37_2_fu_879_p2;
wire   [0:0] xor_ln34_fu_903_p2;
wire   [0:0] or_ln34_fu_913_p2;
wire   [0:0] xor_ln34_1_fu_917_p2;
wire   [0:0] and_ln34_fu_908_p2;
wire   [0:0] and_ln34_1_fu_923_p2;
wire   [17:0] a_fu_937_p9;
wire   [2:0] a_fu_937_p10;
wire   [53:0] zext_ln35_2_fu_970_p1;
wire   [53:0] ashr_ln35_fu_973_p2;
wire   [0:0] icmp_ln35_3_fu_958_p2;
wire   [17:0] trunc_ln35_4_fu_978_p1;
wire   [17:0] select_ln35_4_fu_963_p3;
wire   [17:0] select_ln35_1cast_fu_995_p1;
wire   [0:0] icmp_ln35_4_fu_990_p2;
wire   [17:0] shl_ln35_fu_998_p2;
wire   [0:0] xor_ln36_fu_1011_p2;
wire   [0:0] or_ln36_fu_1021_p2;
wire   [0:0] xor_ln36_1_fu_1025_p2;
wire   [0:0] and_ln36_fu_1016_p2;
wire   [0:0] and_ln36_1_fu_1031_p2;
wire   [17:0] c_fu_1045_p9;
wire   [2:0] c_fu_1045_p10;
wire   [53:0] zext_ln37_2_fu_1078_p1;
wire   [53:0] ashr_ln37_fu_1081_p2;
wire   [0:0] icmp_ln37_3_fu_1066_p2;
wire   [17:0] trunc_ln37_4_fu_1086_p1;
wire   [17:0] select_ln37_4_fu_1071_p3;
wire   [17:0] select_ln37_1cast_fu_1103_p1;
wire   [0:0] icmp_ln37_4_fu_1098_p2;
wire   [17:0] shl_ln37_fu_1106_p2;
wire   [0:0] xor_ln35_fu_1119_p2;
wire   [0:0] and_ln35_fu_1124_p2;
wire   [17:0] b_fu_1137_p9;
wire   [2:0] b_fu_1137_p10;
wire   [0:0] xor_ln37_fu_1158_p2;
wire   [0:0] or_ln37_fu_1168_p2;
wire   [0:0] xor_ln37_1_fu_1172_p2;
wire   [0:0] and_ln37_fu_1163_p2;
wire   [0:0] and_ln37_1_fu_1178_p2;
wire   [17:0] d_fu_1192_p9;
wire   [2:0] d_fu_1192_p10;
wire  signed [17:0] d_fu_1192_p11;
wire  signed [17:0] b_fu_1137_p11;
wire  signed [17:0] mul_ln41_fu_1233_p0;
wire  signed [17:0] mul_ln41_fu_1233_p1;
wire   [33:0] shl_ln_fu_1240_p3;
wire  signed [33:0] grp_fu_1307_p3;
(* use_dsp = "no" *) wire   [33:0] add_ln40_fu_1248_p2;
wire   [33:0] shl_ln1_fu_1271_p3;
wire  signed [33:0] grp_fu_1315_p3;
(* use_dsp = "no" *) wire   [33:0] add_ln41_1_fu_1279_p2;
wire  signed [17:0] grp_fu_1315_p0;
wire  signed [17:0] grp_fu_1315_p1;
reg    grp_fu_198_ce;
reg    grp_fu_201_ce;
reg    grp_fu_1307_ce;
reg    grp_fu_1315_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_356;
wire  signed [2:0] a_fu_937_p1;
wire   [2:0] a_fu_937_p3;
wire   [2:0] a_fu_937_p5;
wire   [2:0] a_fu_937_p7;
wire  signed [2:0] c_fu_1045_p1;
wire   [2:0] c_fu_1045_p3;
wire   [2:0] c_fu_1045_p5;
wire   [2:0] c_fu_1045_p7;
wire  signed [2:0] b_fu_1137_p1;
wire   [2:0] b_fu_1137_p3;
wire   [2:0] b_fu_1137_p5;
wire   [2:0] b_fu_1137_p7;
wire  signed [2:0] d_fu_1192_p1;
wire   [2:0] d_fu_1192_p3;
wire   [2:0] d_fu_1192_p5;
wire   [2:0] d_fu_1192_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp8_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp7_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 acc_I_fu_118 = 18'd0;
#0 acc_Q_fu_122 = 18'd0;
#0 i_fu_126 = 31'd0;
#0 ap_done_reg = 1'b0;
end

gnss_correlator_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_198_p0),
    .ce(grp_fu_198_ce),
    .dout(grp_fu_198_p1)
);

gnss_correlator_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_201_p0),
    .ce(grp_fu_201_ce),
    .dout(grp_fu_201_p1)
);

(* dissolve_hierarchy = "yes" *) gnss_correlator_sparsemux_9_3_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 18 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 18 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 18 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 18 ))
sparsemux_9_3_18_1_1_U3(
    .din0(18'd0),
    .din1(trunc_ln34_3_reg_1465),
    .din2(select_ln34_2_reg_1550),
    .din3(select_ln34_3_reg_1555),
    .def(a_fu_937_p9),
    .sel(a_fu_937_p10),
    .dout(a_fu_937_p11)
);

(* dissolve_hierarchy = "yes" *) gnss_correlator_sparsemux_9_3_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 18 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 18 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 18 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 18 ))
sparsemux_9_3_18_1_1_U4(
    .din0(18'd0),
    .din1(trunc_ln36_3_reg_1523),
    .din2(select_ln36_2_reg_1595),
    .din3(select_ln36_3_reg_1600),
    .def(c_fu_1045_p9),
    .sel(c_fu_1045_p10),
    .dout(c_fu_1045_p11)
);

(* dissolve_hierarchy = "yes" *) gnss_correlator_sparsemux_9_3_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 18 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 18 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 18 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 18 ))
sparsemux_9_3_18_1_1_U5(
    .din0(18'd0),
    .din1(trunc_ln35_3_reg_1584),
    .din2(select_ln35_2_reg_1647),
    .din3(select_ln35_3_reg_1652),
    .def(b_fu_1137_p9),
    .sel(b_fu_1137_p10),
    .dout(b_fu_1137_p11)
);

(* dissolve_hierarchy = "yes" *) gnss_correlator_sparsemux_9_3_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 18 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 18 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 18 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 18 ))
sparsemux_9_3_18_1_1_U6(
    .din0(18'd0),
    .din1(trunc_ln37_3_reg_1636),
    .din2(select_ln37_2_reg_1662),
    .din3(select_ln37_3_reg_1667),
    .def(d_fu_1192_p9),
    .sel(d_fu_1192_p10),
    .dout(d_fu_1192_p11)
);

gnss_correlator_mul_18s_18s_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 34 ))
mul_18s_18s_34_1_1_U7(
    .din0(c_reg_1657),
    .din1(a_reg_1642),
    .dout(mul_ln40_fu_1227_p2)
);

gnss_correlator_mul_18s_18s_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 34 ))
mul_18s_18s_34_1_1_U8(
    .din0(mul_ln41_fu_1233_p0),
    .din1(mul_ln41_fu_1233_p1),
    .dout(mul_ln41_fu_1233_p2)
);

gnss_correlator_mac_mulsub_18s_18s_34s_34_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mac_mulsub_18s_18s_34s_34_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d_fu_1192_p11),
    .din1(b_fu_1137_p11),
    .din2(mul_ln40_reg_1694),
    .ce(grp_fu_1307_ce),
    .dout(grp_fu_1307_p3)
);

gnss_correlator_mac_muladd_18s_18s_34s_34_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mac_muladd_18s_18s_34s_34_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1315_p0),
    .din1(grp_fu_1315_p1),
    .din2(mul_ln41_reg_1699),
    .ce(grp_fu_1315_ce),
    .dout(grp_fu_1315_p3)
);

gnss_correlator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp4)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp7)) begin
                ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp8)) begin
                ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp5)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp6)) begin
                ap_block_pp0_stage1_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_356)) begin
        if ((ap_loop_init == 1'b1)) begin
            acc_I_fu_118 <= 18'd0;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            acc_I_fu_118 <= {{add_ln40_fu_1248_p2[33:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        acc_Q_fu_122 <= 18'd0;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        acc_Q_fu_122 <= {{add_ln41_1_fu_1279_p2[33:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln30_fu_250_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_126 <= add_ln30_fu_256_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_126 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        a_reg_1642 <= a_fu_937_p11;
        c_reg_1657 <= c_fu_1045_p11;
        icmp_ln34_1_reg_1446 <= icmp_ln34_1_fu_453_p2;
        icmp_ln34_2_reg_1459 <= icmp_ln34_2_fu_479_p2;
        icmp_ln34_reg_1439 <= icmp_ln34_fu_438_p2;
        icmp_ln36_1_reg_1504 <= icmp_ln36_1_fu_559_p2;
        icmp_ln36_2_reg_1517 <= icmp_ln36_2_fu_585_p2;
        icmp_ln36_reg_1497 <= icmp_ln36_fu_544_p2;
        mul_ln41_reg_1699 <= mul_ln41_fu_1233_p2;
        select_ln34_1_reg_1451 <= select_ln34_1_fu_471_p3;
        select_ln34_reg_1434 <= select_ln34_fu_431_p3;
        select_ln35_2_reg_1647 <= select_ln35_2_fu_982_p3;
        select_ln35_3_reg_1652 <= select_ln35_3_fu_1003_p3;
        select_ln36_1_reg_1509 <= select_ln36_1_fu_577_p3;
        select_ln36_reg_1492 <= select_ln36_fu_537_p3;
        select_ln37_2_reg_1662 <= select_ln37_2_fu_1090_p3;
        select_ln37_3_reg_1667 <= select_ln37_3_fu_1111_p3;
        tmp_2_reg_1476 <= bitcast_ln726_1_fu_489_p1[32'd63];
        tmp_4_reg_1534 <= bitcast_ln726_3_fu_595_p1[32'd63];
        tmp_5_reg_1540 <= {{bitcast_ln726_3_fu_595_p1[62:52]}};
        tmp_9_reg_1482 <= {{bitcast_ln726_1_fu_489_p1[62:52]}};
        trunc_ln34_3_reg_1465 <= trunc_ln34_3_fu_485_p1;
        trunc_ln35_1_reg_1487 <= trunc_ln35_1_fu_513_p1;
        trunc_ln35_reg_1471 <= trunc_ln35_fu_493_p1;
        trunc_ln36_3_reg_1523 <= trunc_ln36_3_fu_591_p1;
        trunc_ln37_1_reg_1545 <= trunc_ln37_1_fu_619_p1;
        trunc_ln37_reg_1529 <= trunc_ln37_fu_599_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        and_ln35_1_reg_1590 <= and_ln35_1_fu_766_p2;
        icmp_ln35_2_reg_1579 <= icmp_ln35_2_fu_744_p2;
        icmp_ln35_reg_1565 <= icmp_ln35_fu_703_p2;
        icmp_ln37_1_reg_1617 <= icmp_ln37_1_fu_867_p2;
        icmp_ln37_2_reg_1630 <= icmp_ln37_2_fu_893_p2;
        icmp_ln37_reg_1610 <= icmp_ln37_fu_852_p2;
        mul_ln40_reg_1694 <= mul_ln40_fu_1227_p2;
        select_ln34_2_reg_1550 <= select_ln34_2_fu_647_p3;
        select_ln34_3_reg_1555 <= select_ln34_3_fu_668_p3;
        select_ln35_1_reg_1571 <= select_ln35_1_fu_736_p3;
        select_ln35_reg_1560 <= select_ln35_fu_696_p3;
        select_ln36_2_reg_1595 <= select_ln36_2_fu_796_p3;
        select_ln36_3_reg_1600 <= select_ln36_3_fu_817_p3;
        select_ln37_1_reg_1622 <= select_ln37_1_fu_885_p3;
        select_ln37_reg_1605 <= select_ln37_fu_845_p3;
        sext_ln40_1_reg_1677 <= sext_ln40_1_fu_1216_p1;
        sext_ln40_2_reg_1682 <= sext_ln40_2_fu_1219_p1;
        sext_ln40_3_reg_1688 <= sext_ln40_3_fu_1223_p1;
        sext_ln40_reg_1672 <= sext_ln40_fu_1213_p1;
        tmp_1_reg_1393 <= {{bitcast_ln726_fu_345_p1[62:52]}};
        tmp_3_reg_1413 <= bitcast_ln726_2_fu_378_p1[32'd63];
        tmp_reg_1387 <= bitcast_ln726_fu_345_p1[32'd63];
        tmp_s_reg_1419 <= {{bitcast_ln726_2_fu_378_p1[62:52]}};
        trunc_ln34_1_reg_1398 <= trunc_ln34_1_fu_369_p1;
        trunc_ln34_reg_1382 <= trunc_ln34_fu_349_p1;
        trunc_ln35_3_reg_1584 <= trunc_ln35_3_fu_750_p1;
        trunc_ln36_1_reg_1424 <= trunc_ln36_1_fu_402_p1;
        trunc_ln36_reg_1408 <= trunc_ln36_fu_382_p1;
        trunc_ln37_3_reg_1636 <= trunc_ln37_3_fu_899_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem0_addr_1_reg_1354 <= sext_ln35_fu_288_p1;
        gmem0_addr_reg_1348 <= sext_ln34_fu_272_p1;
        gmem1_addr_1_reg_1366 <= sext_ln37_fu_320_p1;
        gmem1_addr_reg_1360 <= sext_ln36_fu_304_p1;
        icmp_ln30_reg_1344 <= icmp_ln30_fu_250_p2;
        icmp_ln30_reg_1344_pp0_iter1_reg <= icmp_ln30_reg_1344;
        icmp_ln30_reg_1344_pp0_iter2_reg <= icmp_ln30_reg_1344_pp0_iter1_reg;
        icmp_ln30_reg_1344_pp0_iter3_reg <= icmp_ln30_reg_1344_pp0_iter2_reg;
        icmp_ln30_reg_1344_pp0_iter4_reg <= icmp_ln30_reg_1344_pp0_iter3_reg;
        icmp_ln30_reg_1344_pp0_iter5_reg <= icmp_ln30_reg_1344_pp0_iter4_reg;
        icmp_ln30_reg_1344_pp0_iter6_reg <= icmp_ln30_reg_1344_pp0_iter5_reg;
        icmp_ln30_reg_1344_pp0_iter7_reg <= icmp_ln30_reg_1344_pp0_iter6_reg;
        icmp_ln30_reg_1344_pp0_iter8_reg <= icmp_ln30_reg_1344_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)))) begin
        reg_204 <= m_axi_gmem0_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp6) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg)))) begin
        reg_208 <= m_axi_gmem1_0_RDATA;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln30_reg_1344_pp0_iter8_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        acc_I_out_ap_vld = 1'b1;
    end else begin
        acc_I_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln30_reg_1344_pp0_iter8_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        acc_Q_out_ap_vld = 1'b1;
    end else begin
        acc_Q_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln30_reg_1344 == 1'd0))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 31'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_126;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (icmp_ln30_reg_1344 == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3)))) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg) & (1'b0 == ap_block_pp0_stage0_grp7)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp5) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (icmp_ln30_reg_1344 == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (1'b0 == ap_block_pp0_stage0_grp4)))) begin
        gmem1_blk_n_AR = m_axi_gmem1_0_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (1'b0 == ap_block_pp0_stage0_grp8)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp6) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg)))) begin
        gmem1_blk_n_R = m_axi_gmem1_0_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_1307_ce = 1'b1;
    end else begin
        grp_fu_1307_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_1315_ce = 1'b1;
    end else begin
        grp_fu_1315_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_198_ce = 1'b1;
    end else begin
        grp_fu_198_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
            grp_fu_198_p0 = bitcast_ln35_fu_373_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
            grp_fu_198_p0 = bitcast_ln34_fu_335_p1;
        end else begin
            grp_fu_198_p0 = 'bx;
        end
    end else begin
        grp_fu_198_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_201_ce = 1'b1;
    end else begin
        grp_fu_201_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
            grp_fu_201_p0 = bitcast_ln37_fu_406_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
            grp_fu_201_p0 = bitcast_ln36_fu_340_p1;
        end else begin
            grp_fu_201_p0 = 'bx;
        end
    end else begin
        grp_fu_201_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        m_axi_gmem0_0_ARADDR = gmem0_addr_1_reg_1354;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (icmp_ln30_reg_1344 == 1'd1))) begin
        m_axi_gmem0_0_ARADDR = gmem0_addr_reg_1348;
    end else begin
        m_axi_gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (icmp_ln30_reg_1344 == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg))) begin
        m_axi_gmem1_0_ARADDR = gmem1_addr_1_reg_1366;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (icmp_ln30_reg_1344 == 1'd1))) begin
        m_axi_gmem1_0_ARADDR = gmem1_addr_reg_1360;
    end else begin
        m_axi_gmem1_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (icmp_ln30_reg_1344 == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)))) begin
        m_axi_gmem1_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp6) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg)))) begin
        m_axi_gmem1_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0 == 1'b1) & (ap_done_pending_pp0 == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_937_p10 = {{{icmp_ln34_reg_1439}, {and_ln34_fu_908_p2}}, {and_ln34_1_fu_923_p2}};

assign a_fu_937_p9 = 'bx;

assign acc_I_out = acc_I_fu_118;

assign acc_Q_out = acc_Q_fu_122;

assign add_ln30_fu_256_p2 = (ap_sig_allocacmp_i_1 + 31'd1);

assign add_ln34_1_fu_459_p2 = ($signed(trunc_ln34_2_fu_449_p1) + $signed(11'd2032));

assign add_ln34_fu_266_p2 = ($signed(zext_ln30_fu_262_p1) + $signed(sext_ln30_cast_fu_224_p1));

assign add_ln35_1_fu_724_p2 = ($signed(trunc_ln35_2_fu_714_p1) + $signed(11'd2032));

assign add_ln35_fu_282_p2 = ($signed(zext_ln30_fu_262_p1) + $signed(sext_ln30_1_cast_fu_220_p1));

assign add_ln36_1_fu_565_p2 = ($signed(trunc_ln36_2_fu_555_p1) + $signed(11'd2032));

assign add_ln36_fu_298_p2 = ($signed(zext_ln30_fu_262_p1) + $signed(sext_ln30_2_cast_fu_216_p1));

assign add_ln37_1_fu_873_p2 = ($signed(trunc_ln37_2_fu_863_p1) + $signed(11'd2032));

assign add_ln37_fu_314_p2 = ($signed(zext_ln30_fu_262_p1) + $signed(sext_ln30_3_cast_fu_212_p1));

assign add_ln40_fu_1248_p2 = ($signed(shl_ln_fu_1240_p3) + $signed(grp_fu_1307_p3));

assign add_ln41_1_fu_1279_p2 = ($signed(shl_ln1_fu_1271_p3) + $signed(grp_fu_1315_p3));

assign and_ln34_1_fu_923_p2 = (xor_ln34_1_fu_917_p2 & icmp_ln34_1_reg_1446);

assign and_ln34_fu_908_p2 = (xor_ln34_fu_903_p2 & icmp_ln34_2_reg_1459);

assign and_ln35_1_fu_766_p2 = (xor_ln35_1_fu_760_p2 & icmp_ln35_1_fu_718_p2);

assign and_ln35_fu_1124_p2 = (xor_ln35_fu_1119_p2 & icmp_ln35_2_reg_1579);

assign and_ln36_1_fu_1031_p2 = (xor_ln36_1_fu_1025_p2 & icmp_ln36_1_reg_1504);

assign and_ln36_fu_1016_p2 = (xor_ln36_fu_1011_p2 & icmp_ln36_2_reg_1517);

assign and_ln37_1_fu_1178_p2 = (xor_ln37_1_fu_1172_p2 & icmp_ln37_1_reg_1617);

assign and_ln37_fu_1163_p2 = (xor_ln37_fu_1158_p2 & icmp_ln37_2_reg_1630);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem1_0_ARREADY == 1'b0)) | ((m_axi_gmem0_0_ARREADY == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem1_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp7 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp8 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem1_0_ARREADY == 1'b0)) | ((m_axi_gmem0_0_ARREADY == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp4 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem1_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp7 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp8 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage1_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)))) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)))));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp5 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp6 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)))) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)))));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp5 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp6 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp6_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((m_axi_gmem0_0_ARREADY == 1'b0) & (icmp_ln30_reg_1344 == 1'd1));
end

always @ (*) begin
    ap_block_state2_io_grp2 = ((icmp_ln30_reg_1344 == 1'd1) & (m_axi_gmem1_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_356 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign ashr_ln34_fu_638_p2 = $signed(select_ln34_reg_1434) >>> zext_ln34_2_fu_635_p1;

assign ashr_ln35_fu_973_p2 = $signed(select_ln35_reg_1560) >>> zext_ln35_2_fu_970_p1;

assign ashr_ln36_fu_787_p2 = $signed(select_ln36_reg_1492) >>> zext_ln36_2_fu_784_p1;

assign ashr_ln37_fu_1081_p2 = $signed(select_ln37_reg_1605) >>> zext_ln37_2_fu_1078_p1;

assign b_fu_1137_p10 = {{{icmp_ln35_reg_1565}, {and_ln35_fu_1124_p2}}, {and_ln35_1_reg_1590}};

assign b_fu_1137_p9 = 'bx;

assign bitcast_ln34_fu_335_p1 = reg_204;

assign bitcast_ln35_fu_373_p1 = reg_204;

assign bitcast_ln36_fu_340_p1 = reg_208;

assign bitcast_ln37_fu_406_p1 = reg_208;

assign bitcast_ln726_1_fu_489_p1 = grp_fu_198_p1;

assign bitcast_ln726_2_fu_378_p1 = grp_fu_201_p1;

assign bitcast_ln726_3_fu_595_p1 = grp_fu_201_p1;

assign bitcast_ln726_fu_345_p1 = grp_fu_198_p1;

assign c_fu_1045_p10 = {{{icmp_ln36_reg_1497}, {and_ln36_fu_1016_p2}}, {and_ln36_1_fu_1031_p2}};

assign c_fu_1045_p9 = 'bx;

assign d_fu_1192_p10 = {{{icmp_ln37_reg_1610}, {and_ln37_fu_1163_p2}}, {and_ln37_1_fu_1178_p2}};

assign d_fu_1192_p9 = 'bx;

assign grp_fu_1315_p0 = sext_ln40_reg_1672;

assign grp_fu_1315_p1 = sext_ln40_3_reg_1688;

assign icmp_ln30_fu_250_p2 = (($signed(zext_ln30_1_fu_246_p1) < $signed(num_samples)) ? 1'b1 : 1'b0);

assign icmp_ln34_1_fu_453_p2 = (($signed(sub_ln34_1_fu_443_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln34_2_fu_479_p2 = ((sub_ln34_1_fu_443_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln34_3_fu_623_p2 = ((select_ln34_1_reg_1451 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln34_4_fu_655_p2 = ((select_ln34_1_reg_1451 < 11'd18) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_438_p2 = ((trunc_ln34_reg_1382 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln35_1_fu_718_p2 = (($signed(sub_ln35_1_fu_708_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln35_2_fu_744_p2 = ((sub_ln35_1_fu_708_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln35_3_fu_958_p2 = ((select_ln35_1_reg_1571 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln35_4_fu_990_p2 = ((select_ln35_1_reg_1571 < 11'd18) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_703_p2 = ((trunc_ln35_reg_1471 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln36_1_fu_559_p2 = (($signed(sub_ln36_1_fu_549_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln36_2_fu_585_p2 = ((sub_ln36_1_fu_549_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln36_3_fu_772_p2 = ((select_ln36_1_reg_1509 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln36_4_fu_804_p2 = ((select_ln36_1_reg_1509 < 11'd18) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_544_p2 = ((trunc_ln36_reg_1408 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln37_1_fu_867_p2 = (($signed(sub_ln37_1_fu_857_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln37_2_fu_893_p2 = ((sub_ln37_1_fu_857_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln37_3_fu_1066_p2 = ((select_ln37_1_reg_1622 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln37_4_fu_1098_p2 = ((select_ln37_1_reg_1622 < 11'd18) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_852_p2 = ((trunc_ln37_reg_1529 == 63'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 64'd1;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 32'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 4'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 64'd1;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_AWADDR = 64'd0;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 32'd0;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_AWVALID = 1'b0;

assign m_axi_gmem1_0_BREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = 32'd0;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 4'd0;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign m_axi_gmem1_0_WVALID = 1'b0;

assign mul_ln41_fu_1233_p0 = sext_ln40_2_reg_1682;

assign mul_ln41_fu_1233_p1 = sext_ln40_1_reg_1677;

assign or_ln34_fu_913_p2 = (icmp_ln34_reg_1439 | icmp_ln34_2_reg_1459);

assign or_ln35_fu_754_p2 = (icmp_ln35_fu_703_p2 | icmp_ln35_2_fu_744_p2);

assign or_ln36_fu_1021_p2 = (icmp_ln36_reg_1497 | icmp_ln36_2_reg_1517);

assign or_ln37_fu_1168_p2 = (icmp_ln37_reg_1610 | icmp_ln37_2_reg_1630);

assign select_ln34_1_fu_471_p3 = ((icmp_ln34_1_fu_453_p2[0:0] == 1'b1) ? add_ln34_1_fu_459_p2 : sub_ln34_2_fu_465_p2);

assign select_ln34_1cast_fu_660_p1 = select_ln34_1_reg_1451;

assign select_ln34_2_fu_647_p3 = ((icmp_ln34_3_fu_623_p2[0:0] == 1'b1) ? trunc_ln34_4_fu_643_p1 : select_ln34_4_fu_628_p3);

assign select_ln34_3_fu_668_p3 = ((icmp_ln34_4_fu_655_p2[0:0] == 1'b1) ? shl_ln34_fu_663_p2 : 18'd0);

assign select_ln34_4_fu_628_p3 = ((tmp_reg_1387[0:0] == 1'b1) ? 18'd262143 : 18'd0);

assign select_ln34_fu_431_p3 = ((tmp_reg_1387[0:0] == 1'b1) ? sub_ln34_fu_425_p2 : zext_ln34_1_fu_421_p1);

assign select_ln35_1_fu_736_p3 = ((icmp_ln35_1_fu_718_p2[0:0] == 1'b1) ? add_ln35_1_fu_724_p2 : sub_ln35_2_fu_730_p2);

assign select_ln35_1cast_fu_995_p1 = select_ln35_1_reg_1571;

assign select_ln35_2_fu_982_p3 = ((icmp_ln35_3_fu_958_p2[0:0] == 1'b1) ? trunc_ln35_4_fu_978_p1 : select_ln35_4_fu_963_p3);

assign select_ln35_3_fu_1003_p3 = ((icmp_ln35_4_fu_990_p2[0:0] == 1'b1) ? shl_ln35_fu_998_p2 : 18'd0);

assign select_ln35_4_fu_963_p3 = ((tmp_2_reg_1476[0:0] == 1'b1) ? 18'd262143 : 18'd0);

assign select_ln35_fu_696_p3 = ((tmp_2_reg_1476[0:0] == 1'b1) ? sub_ln35_fu_690_p2 : zext_ln35_1_fu_686_p1);

assign select_ln36_1_fu_577_p3 = ((icmp_ln36_1_fu_559_p2[0:0] == 1'b1) ? add_ln36_1_fu_565_p2 : sub_ln36_2_fu_571_p2);

assign select_ln36_1cast_fu_809_p1 = select_ln36_1_reg_1509;

assign select_ln36_2_fu_796_p3 = ((icmp_ln36_3_fu_772_p2[0:0] == 1'b1) ? trunc_ln36_4_fu_792_p1 : select_ln36_4_fu_777_p3);

assign select_ln36_3_fu_817_p3 = ((icmp_ln36_4_fu_804_p2[0:0] == 1'b1) ? shl_ln36_fu_812_p2 : 18'd0);

assign select_ln36_4_fu_777_p3 = ((tmp_3_reg_1413[0:0] == 1'b1) ? 18'd262143 : 18'd0);

assign select_ln36_fu_537_p3 = ((tmp_3_reg_1413[0:0] == 1'b1) ? sub_ln36_fu_531_p2 : zext_ln36_1_fu_527_p1);

assign select_ln37_1_fu_885_p3 = ((icmp_ln37_1_fu_867_p2[0:0] == 1'b1) ? add_ln37_1_fu_873_p2 : sub_ln37_2_fu_879_p2);

assign select_ln37_1cast_fu_1103_p1 = select_ln37_1_reg_1622;

assign select_ln37_2_fu_1090_p3 = ((icmp_ln37_3_fu_1066_p2[0:0] == 1'b1) ? trunc_ln37_4_fu_1086_p1 : select_ln37_4_fu_1071_p3);

assign select_ln37_3_fu_1111_p3 = ((icmp_ln37_4_fu_1098_p2[0:0] == 1'b1) ? shl_ln37_fu_1106_p2 : 18'd0);

assign select_ln37_4_fu_1071_p3 = ((tmp_4_reg_1534[0:0] == 1'b1) ? 18'd262143 : 18'd0);

assign select_ln37_fu_845_p3 = ((tmp_4_reg_1534[0:0] == 1'b1) ? sub_ln37_fu_839_p2 : zext_ln37_1_fu_835_p1);

assign sext_ln30_1_cast_fu_220_p1 = $signed(sext_ln30_1);

assign sext_ln30_2_cast_fu_216_p1 = $signed(sext_ln30_2);

assign sext_ln30_3_cast_fu_212_p1 = $signed(sext_ln30_3);

assign sext_ln30_cast_fu_224_p1 = $signed(sext_ln30);

assign sext_ln34_fu_272_p1 = $signed(add_ln34_fu_266_p2);

assign sext_ln35_fu_288_p1 = $signed(add_ln35_fu_282_p2);

assign sext_ln36_fu_304_p1 = $signed(add_ln36_fu_298_p2);

assign sext_ln37_fu_320_p1 = $signed(add_ln37_fu_314_p2);

assign sext_ln40_1_fu_1216_p1 = a_reg_1642;

assign sext_ln40_2_fu_1219_p1 = d_fu_1192_p11;

assign sext_ln40_3_fu_1223_p1 = b_fu_1137_p11;

assign sext_ln40_fu_1213_p1 = c_reg_1657;

assign shl_ln1_fu_1271_p3 = {{acc_Q_fu_122}, {16'd0}};

assign shl_ln34_fu_663_p2 = trunc_ln34_3_reg_1465 << select_ln34_1cast_fu_660_p1;

assign shl_ln35_fu_998_p2 = trunc_ln35_3_reg_1584 << select_ln35_1cast_fu_995_p1;

assign shl_ln36_fu_812_p2 = trunc_ln36_3_reg_1523 << select_ln36_1cast_fu_809_p1;

assign shl_ln37_fu_1106_p2 = trunc_ln37_3_reg_1636 << select_ln37_1cast_fu_1103_p1;

assign shl_ln_fu_1240_p3 = {{acc_I_fu_118}, {16'd0}};

assign sub_ln34_1_fu_443_p2 = (12'd1075 - zext_ln34_fu_411_p1);

assign sub_ln34_2_fu_465_p2 = (11'd16 - trunc_ln34_2_fu_449_p1);

assign sub_ln34_fu_425_p2 = (54'd0 - zext_ln34_1_fu_421_p1);

assign sub_ln35_1_fu_708_p2 = (12'd1075 - zext_ln35_fu_676_p1);

assign sub_ln35_2_fu_730_p2 = (11'd16 - trunc_ln35_2_fu_714_p1);

assign sub_ln35_fu_690_p2 = (54'd0 - zext_ln35_1_fu_686_p1);

assign sub_ln36_1_fu_549_p2 = (12'd1075 - zext_ln36_fu_517_p1);

assign sub_ln36_2_fu_571_p2 = (11'd16 - trunc_ln36_2_fu_555_p1);

assign sub_ln36_fu_531_p2 = (54'd0 - zext_ln36_1_fu_527_p1);

assign sub_ln37_1_fu_857_p2 = (12'd1075 - zext_ln37_fu_825_p1);

assign sub_ln37_2_fu_879_p2 = (11'd16 - trunc_ln37_2_fu_863_p1);

assign sub_ln37_fu_839_p2 = (54'd0 - zext_ln37_1_fu_835_p1);

assign trunc_ln34_1_fu_369_p1 = bitcast_ln726_fu_345_p1[51:0];

assign trunc_ln34_2_fu_449_p1 = sub_ln34_1_fu_443_p2[10:0];

assign trunc_ln34_3_fu_485_p1 = select_ln34_fu_431_p3[17:0];

assign trunc_ln34_4_fu_643_p1 = ashr_ln34_fu_638_p2[17:0];

assign trunc_ln34_fu_349_p1 = bitcast_ln726_fu_345_p1[62:0];

assign trunc_ln35_1_fu_513_p1 = bitcast_ln726_1_fu_489_p1[51:0];

assign trunc_ln35_2_fu_714_p1 = sub_ln35_1_fu_708_p2[10:0];

assign trunc_ln35_3_fu_750_p1 = select_ln35_fu_696_p3[17:0];

assign trunc_ln35_4_fu_978_p1 = ashr_ln35_fu_973_p2[17:0];

assign trunc_ln35_fu_493_p1 = bitcast_ln726_1_fu_489_p1[62:0];

assign trunc_ln36_1_fu_402_p1 = bitcast_ln726_2_fu_378_p1[51:0];

assign trunc_ln36_2_fu_555_p1 = sub_ln36_1_fu_549_p2[10:0];

assign trunc_ln36_3_fu_591_p1 = select_ln36_fu_537_p3[17:0];

assign trunc_ln36_4_fu_792_p1 = ashr_ln36_fu_787_p2[17:0];

assign trunc_ln36_fu_382_p1 = bitcast_ln726_2_fu_378_p1[62:0];

assign trunc_ln37_1_fu_619_p1 = bitcast_ln726_3_fu_595_p1[51:0];

assign trunc_ln37_2_fu_863_p1 = sub_ln37_1_fu_857_p2[10:0];

assign trunc_ln37_3_fu_899_p1 = select_ln37_fu_845_p3[17:0];

assign trunc_ln37_4_fu_1086_p1 = ashr_ln37_fu_1081_p2[17:0];

assign trunc_ln37_fu_599_p1 = bitcast_ln726_3_fu_595_p1[62:0];

assign xor_ln34_1_fu_917_p2 = (or_ln34_fu_913_p2 ^ 1'd1);

assign xor_ln34_fu_903_p2 = (icmp_ln34_reg_1439 ^ 1'd1);

assign xor_ln35_1_fu_760_p2 = (or_ln35_fu_754_p2 ^ 1'd1);

assign xor_ln35_fu_1119_p2 = (icmp_ln35_reg_1565 ^ 1'd1);

assign xor_ln36_1_fu_1025_p2 = (or_ln36_fu_1021_p2 ^ 1'd1);

assign xor_ln36_fu_1011_p2 = (icmp_ln36_reg_1497 ^ 1'd1);

assign xor_ln37_1_fu_1172_p2 = (or_ln37_fu_1168_p2 ^ 1'd1);

assign xor_ln37_fu_1158_p2 = (icmp_ln37_reg_1610 ^ 1'd1);

assign zext_ln30_1_fu_246_p1 = ap_sig_allocacmp_i_1;

assign zext_ln30_fu_262_p1 = ap_sig_allocacmp_i_1;

assign zext_ln34_1_cast_fu_414_p3 = {{1'd1}, {trunc_ln34_1_reg_1398}};

assign zext_ln34_1_fu_421_p1 = zext_ln34_1_cast_fu_414_p3;

assign zext_ln34_2_fu_635_p1 = select_ln34_1_reg_1451;

assign zext_ln34_fu_411_p1 = tmp_1_reg_1393;

assign zext_ln35_1_cast_fu_679_p3 = {{1'd1}, {trunc_ln35_1_reg_1487}};

assign zext_ln35_1_fu_686_p1 = zext_ln35_1_cast_fu_679_p3;

assign zext_ln35_2_fu_970_p1 = select_ln35_1_reg_1571;

assign zext_ln35_fu_676_p1 = tmp_9_reg_1482;

assign zext_ln36_1_cast_fu_520_p3 = {{1'd1}, {trunc_ln36_1_reg_1424}};

assign zext_ln36_1_fu_527_p1 = zext_ln36_1_cast_fu_520_p3;

assign zext_ln36_2_fu_784_p1 = select_ln36_1_reg_1509;

assign zext_ln36_fu_517_p1 = tmp_s_reg_1419;

assign zext_ln37_1_cast_fu_828_p3 = {{1'd1}, {trunc_ln37_1_reg_1545}};

assign zext_ln37_1_fu_835_p1 = zext_ln37_1_cast_fu_828_p3;

assign zext_ln37_2_fu_1078_p1 = select_ln37_1_reg_1622;

assign zext_ln37_fu_825_p1 = tmp_5_reg_1540;

endmodule //gnss_correlator_gnss_correlator_Pipeline_VITIS_LOOP_30_1
